Repository kontena/pharos-cluster, pull requests merged in 2018-05, with the labels that each got.

#342 Fix examples cluster.yml trusted_subnets
  examples/terraform-aws/cluster.yml
  examples/vagrant/cluster.yml
Labels: chore, documentation

#349 Pin dry-versions
  pharos-cluster.gemspec
Labels: bug

#348 Fix horizontal-pod-autoscaler-use-rest-clients
  lib/pharos/phases/configure_master.rb
Labels: bug

#343 Fix examples for new --tf-json syntax
  examples/terraform-aws/README.md
  examples/terraform-do/README.md
  examples/terraform-packet/README.md
Labels: documentation

#352 Update kured to version master-b27aaa1
  lib/pharos/addons/kured.rb
Labels: bug

#347 Add config option to enable kubelet read-only port
  lib/pharos/config.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/host.rb
  lib/pharos/configuration/kubelet.rb
  lib/pharos/phases/configure_kubelet.rb
  spec/pharos/phases/configure_kubelet_spec.rb
Labels: enhancement

#356 Use master.api_address in addon
  lib/pharos/addon.rb
  spec/pharos/addon_spec.rb
Labels: bug

#359 Fix kubelet config defaulting
  lib/pharos/config_schema.rb
  spec/pharos/config_schema_spec.rb
  spec/pharos/config_spec.rb
  spec/pharos/up_command_spec.rb
Labels: bug

#364 rubocop: Disable Lint/SplatKeywordArguments
  .rubocop.yml
Labels: chore

#366 Configurable node taints
  lib/pharos/autoload.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/host.rb
  lib/pharos/configuration/taint.rb
  lib/pharos/phases/configure_master.rb
  lib/pharos/phases/label_node.rb
  spec/pharos/config_spec.rb
  spec/pharos/phases/configure_master_spec.rb
  spec/pharos/phases/label_node_spec.rb
Labels: enhancement

#373 Remove broken ConfiureEtcd --name migration logic
  lib/pharos/phases/configure_etcd.rb
Labels: bug

#376 Always disable apt unattended-upgrade
  lib/pharos/scripts/configure-essentials.sh
Labels: bug

#277 Refactor master phases
  lib/pharos/autoload.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/kubeadm.rb
  lib/pharos/phases/configure_master.rb
  lib/pharos/phases/setup_master.rb
  lib/pharos/phases/upgrade_master.rb
  spec/pharos/kubeadm_spec.rb
Labels: enhancement

#308 Install crictl if using crio
  lib/pharos/phases/configure_host.rb
  lib/pharos/scripts/configure-cri-o.sh
  lib/pharos/scripts/repos/cri-o.sh
  lib/pharos/terraform/json_parser.rb
  lib/pharos_cluster.rb
Labels: enhancement

#385 Configurable image_repository
  lib/pharos/config.rb
  lib/pharos/config_schema.rb
  lib/pharos/kubeadm.rb
  lib/pharos/phases/configure_calico.rb
  lib/pharos/phases/configure_etcd.rb
  lib/pharos/phases/configure_host.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_metrics.rb
  lib/pharos/phases/configure_weave.rb
  lib/pharos/resources/calico/daemonset.yml.erb
  lib/pharos/resources/heapster/deployment.yml.erb
  lib/pharos/resources/weave/daemon-set.yml.erb
  lib/pharos/scripts/configure-cri-o.sh
  lib/pharos/scripts/configure-etcd.sh
  lib/pharos/scripts/configure-kubelet-proxy.sh
  lib/pharos_cluster.rb
  spec/pharos/phases/configure_kubelet_spec.rb
Labels: enhancement

#389 Configurable http proxy per host
  examples/vagrant/Vagrantfile
  examples/vagrant/proxy-only.sh
  lib/pharos/config_schema.rb
  lib/pharos/configuration/host.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_host.rb
  lib/pharos/scripts/configure-cri-o.sh
  lib/pharos/scripts/configure-docker.sh
  lib/pharos/scripts/configure-essentials.sh
  lib/pharos/scripts/configure-etcd.sh
  lib/pharos/scripts/pharos.sh
Labels: enhancement

#382 Allow to pass addon config from terraform
  lib/pharos/addon.rb
  lib/pharos/terraform/json_parser.rb
  lib/pharos/up_command.rb
  spec/fixtures/terraform/with_addons.json
  spec/pharos/terraform/json_parser_spec.rb
Labels: enhancement

#391 Download cfssl from pharos repository
  lib/pharos/scripts/configure-cfssl.sh
Labels: chore, enhancement
