Repository kontena/pharos-cluster, pull requests merged in 2018-04, with the labels that each got.

#176 Add kubernetes-dashboard to readme
  README.md
Labels: chore

#164 Initial support for cloud provider
  lib/pharos/config.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/cloud.rb
  lib/pharos/configuration/host.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_master.rb
  lib/pharos/phases/join_node.rb
  lib/pharos/phases/validate_host.rb
  lib/pharos/up_command.rb
  spec/pharos/config_schema_spec.rb
Labels: enhancement

#178 Fix typo in readme
  README.md
Labels: chore

#179 Fix ConfigureKubelet
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_master.rb
Labels: bug

#180 Add cloud provider to readme
  README.md
Labels: chore

#187 README: Document the hosts section of cluster.yml
  README.md
Labels: documentation

#185 README: Mention passwordless sudo requirement
  README.md
Labels: documentation

#189 Limit access to the weave status port
  lib/pharos/resources/weave/daemon-set.yml
Labels: bug

#191 Add slack badge to readme
  README.md
Labels: chore

#192 Fix kubelet --cluster-dns for customized network service_cidr
  lib/pharos/configuration/network.rb
  lib/pharos/phases/configure_kubelet.rb
  spec/pharos/phases/configure_kubelet_spec.rb
Labels: bug

#195 Configure kubelet on master when not installing/upgrading
  lib/pharos/phases/configure_master.rb
Labels: bug

#201 Use Pharos::YamlFile in phases/base parse_resource_file
  lib/pharos/phases/base.rb
  lib/pharos/phases/configure_master.rb
Labels: bug

#193 Re-disable unauthenticated kubelet --read-only-port
  lib/pharos/phases/configure_kubelet.rb
  spec/pharos/phases/configure_kubelet_spec.rb
Labels: bug

#197 Option to read hosts from terraform output json
  README.md
  examples/terraform-do/README.md
  examples/terraform-do/cluster.yml
  examples/terraform-do/main.tf
  lib/pharos/autoload.rb
  lib/pharos/terraform/json_parser.rb
  lib/pharos/up_command.rb
  spec/fixtures/tf.json
  spec/pharos/terraform/json_parser_spec.rb
  spec/pharos/up_command_spec.rb
  spec/spec_helper.rb
  spec/support/fixtures_dir_helper.rb
  spec/support/fixtures_helper.rb
Labels: enhancement

#206 Fix terraform-do main.tf
  examples/terraform-do/main.tf
Labels: chore

#209 Move Pharos::Kube::Client to separate file
  lib/pharos/kube.rb
  lib/pharos/kube/client.rb
Labels: chore

#207 Support ed25519
  pharos-cluster.gemspec
Labels: enhancement

#211 Don't colorize output when stdout is redirected
  lib/pharos/command.rb
  lib/pharos/ssh/client.rb
Labels: enhancement

#218 Show info about kubeconfig at the end
  lib/pharos/up_command.rb
Labels: enhancement

#217 Document open ports (required, monitoring, restricted)
  README.md
Labels: documentation

#223 Refactor SSH client
  lib/pharos/autoload.rb
  lib/pharos/phases/base.rb
  lib/pharos/phases/configure_client.rb
  lib/pharos/phases/configure_host.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_master.rb
  lib/pharos/phases/join_node.rb
  lib/pharos/phases/validate_host.rb
  lib/pharos/ssh/client.rb
  lib/pharos/ssh/remote_command.rb
  lib/pharos/ssh/remote_file.rb
  lib/pharos/ssh/tempfile.rb
Labels: enhancement

#111 Refactor phases to run in parallel across nodes
  lib/pharos/addon.rb
  lib/pharos/addon_manager.rb
  lib/pharos/addons/ingress_nginx.rb
  lib/pharos/addons/kubernetes_dashboard.rb
  lib/pharos/autoload.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/config.rb
  lib/pharos/configuration/host.rb
  lib/pharos/logging.rb
  lib/pharos/phase.rb
  lib/pharos/phase_manager.rb
  lib/pharos/phases.rb
  lib/pharos/phases/base.rb
  lib/pharos/phases/component.rb
  lib/pharos/phases/configure_bootstrap.rb
  lib/pharos/phases/configure_client.rb
  lib/pharos/phases/configure_dns.rb
  lib/pharos/phases/configure_host.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_master.rb
  lib/pharos/phases/configure_metrics.rb
  lib/pharos/phases/configure_network.rb
  lib/pharos/phases/join_node.rb
  lib/pharos/phases/label_node.rb
  lib/pharos/phases/logging.rb
  lib/pharos/phases/store_cluster_yaml.rb
  lib/pharos/phases/validate_host.rb
  lib/pharos/ssh/client.rb
  lib/pharos/ssh/manager.rb
  lib/pharos/up_command.rb
  spec/pharos/addon_spec.rb
  spec/pharos/addons/ingress_nginx_spec.rb
  spec/pharos/phases/configure_dns_spec.rb
  spec/pharos/phases/configure_kubelet_spec.rb
  spec/pharos/phases/configure_master_spec.rb
  spec/pharos/phases/label_node_spec.rb
  spec/pharos/up_command_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#226 Polish up command humanize_duration output
  lib/pharos/up_command.rb
  spec/pharos/up_command_spec.rb
Labels: enhancement

#230 Fix master upgrade regressions
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/configure_master.rb
Labels: bug

#232 Upgrade weave 2.3.0
  README.md
  lib/pharos/phases/configure_network.rb
  lib/pharos/resources/weave/daemon-set.yml.erb
Labels: enhancement

#233 Report config errors to stderr
  lib/pharos/up_command.rb
Labels: bug

#238 Load rbnacl-libsodium before rbnacl
  pharos-cluster.gemspec
Labels: bug

#222 Multi-master support
  README.md
  examples/terraform-do/main.tf
  lib/pharos/addons/kubernetes_dashboard.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/config.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/api.rb
  lib/pharos/configuration/host.rb
  lib/pharos/kube/cert_manager.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_bootstrap.rb
  lib/pharos/phases/configure_cfssl.rb
  lib/pharos/phases/configure_client.rb
  lib/pharos/phases/configure_dns.rb
  lib/pharos/phases/configure_etcd.rb
  lib/pharos/phases/configure_etcd_ca.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_master.rb
  lib/pharos/phases/configure_metrics.rb
  lib/pharos/phases/configure_network.rb
  lib/pharos/phases/join_node.rb
  lib/pharos/phases/label_node.rb
  lib/pharos/scripts/configure-cfssl.sh
  lib/pharos/scripts/configure-etcd-ca.sh
  lib/pharos/scripts/configure-etcd-certs.sh
  lib/pharos/scripts/configure-etcd.sh
  lib/pharos/scripts/configure-kube.sh
  lib/pharos/scripts/configure-kubelet-proxy.sh
  lib/pharos/scripts/install-kubeadm.sh
  lib/pharos/terraform/json_parser.rb
  lib/pharos/up_command.rb
  lib/pharos_cluster.rb
  spec/pharos/phases/configure_master_spec.rb
  spec/pharos/phases/join_node_spec.rb
Labels: enhancement

#243 Cleanup autoload modules
  lib/pharos/autoload.rb
Labels: chore

#246 Store pharos version to configmap
  lib/pharos/phases/store_cluster_yaml.rb
Labels: chore, enhancement

#245 Fix listing of addons
  lib/pharos/version_command.rb
Labels: bug

#248 Fix link in readme
  README.md
Labels: chore

#251 Set DEBIAN_FRONTEND=noninteractive in scripts
  lib/pharos/scripts/configure-cri-o.sh
  lib/pharos/scripts/configure-docker.sh
  lib/pharos/scripts/configure-essentials.sh
  lib/pharos/scripts/configure-kube.sh
  lib/pharos/scripts/configure-kubelet-proxy.sh
  lib/pharos/scripts/install-kubeadm.sh
  lib/pharos/scripts/repos/update.sh
Labels: enhancement

#247 Handle 0.5 -> 0.6 migration
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/configure_master.rb
  lib/pharos/phases/migrate_master.rb
  lib/pharos/phases/migrate_worker.rb
  lib/pharos/scripts/migrations/migrate_master_05_to_06.sh
  lib/pharos/scripts/migrations/migrate_worker_05_to_06.sh
Labels: enhancement

#231 Fix --no-color
  lib/pharos/cluster_manager.rb
  lib/pharos/ssh/remote_command.rb
  lib/pharos/up_command.rb
Labels: bug

#253 Fix missing keyword from Pastel.new for RemoteCommand debug
  lib/pharos/ssh/remote_command.rb
Labels: bug

#254 Fix broken worker migrate if kubelet.conf does not exist
  lib/pharos/phases/migrate_worker.rb
  spec/pharos/phases/migrate_worker_spec.rb
Labels: bug

#255 Add title + specs to MigrateMaster
  lib/pharos/phases/migrate_master.rb
  spec/pharos/phases/migrate_master_spec.rb
Labels: bug, chore

#261 Fix encryption secrets to use the same keys on all master nodes
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/configure_master.rb
  lib/pharos/phases/configure_secrets_encryption.rb
  spec/pharos/phases/configure_encryption_secrets_spec.rb
  spec/pharos/phases/configure_master_spec.rb
Labels: bug

#259 Set apiserver-count
  lib/pharos/phases/configure_master.rb
  spec/pharos/phases/configure_master_spec.rb
Labels: enhancement

#266 Move docs to separate repo
  README.md
Labels: chore, documentation

#273 Fix path to migration script
  lib/pharos/phases/migrate_master.rb
Labels: bug

#276 Fix external etcd
  lib/pharos/cluster_manager.rb
  lib/pharos/config.rb
  lib/pharos/phases/configure_master.rb
Labels: bug

#282 Default addons to empty hash
  lib/pharos/config.rb
  spec/pharos/config_spec.rb
Labels: bug

#279 Turn swap off in etcd / kubelet-proxy dropins
  lib/pharos/scripts/configure-etcd.sh
  lib/pharos/scripts/configure-kubelet-proxy.sh
Labels: bug

#280 Merge api config from terraform only if it exists
  lib/pharos/up_command.rb
  spec/fixtures/terraform/tf.json
  spec/fixtures/terraform/with_api_endpoint.json
  spec/pharos/terraform/json_parser_spec.rb
  spec/pharos/up_command_spec.rb
Labels: bug

#271 Fix rbnacl warnings by upgrading Net::SSH
  pharos-cluster.gemspec
Labels: bug, chore

#284 Update Kubernetes to 1.10.1
  lib/pharos_cluster.rb
Labels: enhancement

#285 Drop Net::SCP
  lib/pharos/ssh/client.rb
  lib/pharos/ssh/remote_file.rb
  pharos-cluster.gemspec
Labels: bug, chore

#288 Use only one key for secrets encryption
  lib/pharos/phases/configure_secrets_encryption.rb
  lib/pharos/resources/secrets/encryption-config.yml.erb
Labels: bug

#297 Avoid false-negatives when checking if file exists on remote host
  lib/pharos/ssh/remote_file.rb
Labels: bug

#265 Support calico as an alternative network provider
  cluster.example.yml
  lib/pharos/cluster_manager.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/network.rb
  lib/pharos/phases/configure_calico.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_weave.rb
  lib/pharos/resources/calico/10-cluster-role.yml
  lib/pharos/resources/calico/11-serviceaccount.yml
  lib/pharos/resources/calico/12-cluster-role-binding.yml
  lib/pharos/resources/calico/configmap.yml.erb
  lib/pharos/resources/calico/crd-bgpconfigurations.yml
  lib/pharos/resources/calico/crd-bgppeers.yml
  lib/pharos/resources/calico/crd-clusterinformations.yml
  lib/pharos/resources/calico/crd-felixconfigurations.yml
  lib/pharos/resources/calico/crd-globalnetworkpolicies.yml
  lib/pharos/resources/calico/crd-globalnetworksets.yml
  lib/pharos/resources/calico/crd-hostendpoints.yml
  lib/pharos/resources/calico/crd-ippools.yml
  lib/pharos/resources/calico/crd-networkpolicies.yml
  lib/pharos/resources/calico/daemonset.yml.erb
Labels: enhancement

#293 Handle add/remove of master hosts
  lib/pharos/autoload.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/configuration/host.rb
  lib/pharos/etcd/client.rb
  lib/pharos/phases/configure_etcd.rb
  lib/pharos/phases/configure_etcd_changes.rb
  lib/pharos/phases/configure_master.rb
  lib/pharos/phases/validate_host.rb
  lib/pharos/scripts/configure-etcd.sh
  lib/pharos/up_command.rb
Labels: enhancement

#272 Terraform AWS example
  examples/terraform-aws/README.md
  examples/terraform-aws/cluster.yml
  examples/terraform-aws/iam.tf
  examples/terraform-aws/main.tf
  examples/terraform-aws/masters.tf
  examples/terraform-aws/output.tf
  examples/terraform-aws/variables.tf
  examples/terraform-aws/workers.tf
Labels: chore, documentation

#313 Terraform Packet.net example
  examples/terraform-packet/README.md
  examples/terraform-packet/cluster.yml
  examples/terraform-packet/main.tf
Labels: chore, documentation

#317 Store complete cluster.yml to configmap
  lib/pharos/cluster_manager.rb
  lib/pharos/config.rb
  lib/pharos/phases/store_cluster_yaml.rb
  lib/pharos/up_command.rb
Labels: chore, enhancement

#321 Fix calico node IP address autodetection to use private addresses if available
  lib/pharos/phases/configure_calico.rb
  lib/pharos/resources/calico/daemonset.yml.erb
Labels: bug

#322 Configurable calico ipip_mode
  lib/pharos/config_schema.rb
  lib/pharos/configuration/network.rb
  lib/pharos/phases/configure_calico.rb
  lib/pharos/resources/calico/daemonset.yml.erb
Labels: documentation, enhancement

#323 Disable only previously enabled addons
  lib/pharos/addon_manager.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_client.rb
  lib/pharos/phases/store_cluster_yaml.rb
  lib/pharos/up_command.rb
  spec/pharos/phases/join_node_spec.rb
Labels: enhancement

#327 Prompt & show config
  lib/pharos/autoload.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/command.rb
  lib/pharos/config.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/kube_proxy.rb
  lib/pharos/phases.rb
  lib/pharos/phases/configure_calico.rb
  lib/pharos/phases/configure_cfssl.rb
  lib/pharos/phases/configure_etcd.rb
  lib/pharos/phases/configure_host.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_metrics.rb
  lib/pharos/phases/configure_weave.rb
  lib/pharos/up_command.rb
  pharos-cluster.gemspec
Labels: enhancement

#326 Fix stack prune
  lib/pharos/kube/client.rb
  lib/pharos/kube/resource.rb
  lib/pharos/kube/session.rb
  lib/pharos/kube/stack.rb
  spec/pharos/kube/stack_spec.rb
Labels: bug

#335 Add pharos kubelet proxy component info
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/scripts/configure-kubelet-proxy.sh
  lib/pharos_cluster.rb
Labels: bug

#336 Fix host role checks to skip unconfigured hosts
  lib/pharos/phases/validate_host.rb
  spec/pharos/phases/validate_host_spec.rb
Labels: bug

#333 Store component and addon versions to configmap
  lib/pharos/addon.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/phases.rb
  lib/pharos/phases/store_cluster_configuration.rb
Labels: enhancement

#339 Install nfs-common as part of configure-kube
  lib/pharos/scripts/configure-kube.sh
Labels: bug
