Repository kontena/pharos-cluster, pull requests merged in 2018-12, with the labels that each got.

#866 Fix debian stretch docker version check
  lib/pharos/host/debian/debian_stretch.rb
Labels: bug

#867 Improve drain during runtime upgrade
  non-oss/pharos_pro/phases/configure_host.rb
Labels: bug, pro

#799 Refactor Pharos::Host::Configurer and drop HostConfigManager
  lib/pharos/autoload.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/config.rb
  lib/pharos/configuration/host.rb
  lib/pharos/host/configurer.rb
  lib/pharos/host/debian/debian_stretch.rb
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
  lib/pharos/host_config_manager.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_cfssl.rb
  lib/pharos/phases/gather_facts.rb
  lib/pharos/phases/validate_host.rb
  non-oss/spec/pharos_pro/addons/kontena_storage_spec.rb
  spec/pharos/configuration/host_spec.rb
  spec/pharos/host/configurer_spec.rb
  spec/pharos/host/ubuntu/ubuntu_xenial_spec.rb
  spec/pharos/phases/configure_kubelet_spec.rb
  spec/pharos/phases/validate_host_spec.rb
Labels: chore, enhancement

#868 Fix cri-o systemd daemon reload
  lib/pharos/host/debian/scripts/configure-cri-o.sh
  lib/pharos/host/el7/scripts/configure-cri-o.sh
  lib/pharos/host/ubuntu/scripts/configure-cri-o.sh
Labels: bug

#862 Optionally configure proxies for control plane
  lib/pharos/config.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/control_plane.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_master.rb
  lib/pharos/scripts/kubeadm-init.sh
  lib/pharos/scripts/kubeadm-reconfigure.sh
  spec/pharos/phases/configure_kubelet_spec.rb
Labels: bug

#870 Install `yum-utils` on EL7
  lib/pharos/host/el7/scripts/configure-essentials.sh
Labels: bug

#873 [v2.0.x] Kubernetes 1.11.5
  lib/pharos_cluster.rb
Labels: bug

#876 Use master host ip address as cluster url in lens config
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: bug

#879 Don't trap SIGPIPE
  bin/pharos-cluster
  e2e/travis.sh
  lib/pharos/command.rb
Labels: bug

#878 Fix misbehaving cri-o upgrades
  lib/pharos/host/configurer.rb
  lib/pharos/host/debian/scripts/configure-cri-o.sh
  lib/pharos/host/debian/scripts/reset.sh
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/el7/scripts/configure-cri-o.sh
  lib/pharos/host/el7/scripts/reset.sh
  lib/pharos/host/ubuntu/scripts/configure-cri-o.sh
  lib/pharos/host/ubuntu/scripts/reset.sh
  lib/pharos/host/ubuntu/ubuntu.rb
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
  spec/pharos/host/ubuntu/ubuntu_xenial_spec.rb
Labels: bug

#880 Apply psp policies on upgrade if they were not previously enabled
  lib/pharos/phases/configure_psp.rb
  lib/pharos/phases/mixins/psp.rb
  lib/pharos/phases/upgrade_master.rb
Labels: bug

#883 E2e: smoke test on DO cluster
  .drone.yml
  e2e/digitalocean/cluster.yml
  e2e/digitalocean/main.tf
  e2e/digitalocean/terraform.tfvars
  e2e/drone.sh
  e2e/drone_setup.sh
  e2e/drone_teardown.sh
Labels: chore

#881 Improve SSH client thread safety
  lib/pharos/ssh/client.rb
Labels: enhancement

#885 Fix uninitialized constant Pharos::Host::Ubuntu::DOCKER_VERSION
  .drone.yml
  lib/pharos/host/ubuntu/ubuntu.rb
  spec/pharos/host/ubuntu/ubuntu_xenial_spec.rb
Labels: bug, chore

#889 Update Kontena Lens to version 1.3.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement, pro

#899 Fix modprobe path on Debian
  lib/pharos/host/debian/scripts/configure-netfilter.sh
Labels: bug

#865 Correct replica location
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/04-user-management-deployment.yml.erb
Labels: bug

#898 Enable flying-shuttle only when multi-region cluster
  lib/pharos/phases/configure_weave.rb
  lib/pharos/resources/weave/daemon-set.yml.erb
Labels: bug, enhancement

#914 Fix bionic crio check
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
Labels: bug

#919 Update ubuntu xenial docker.io version
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
Labels: bug

#922 Do not run teardown if TF apply not done
  e2e/drone_teardown.sh
Labels: chore

#921 Terraform-packet tweaks
  examples/terraform-packet/README.md
  examples/terraform-packet/cluster.yml
  examples/terraform-packet/main.tf
  examples/terraform-packet/pharos-addons/packet-ccm/addon.rb
  examples/terraform-packet/pharos-addons/packet-ccm/resources/00-secret.yml.erb
  examples/terraform-packet/pharos-addons/packet-ccm/resources/01-serviceaccount.yml
  examples/terraform-packet/pharos-addons/packet-ccm/resources/02-clusterrole.yml
  examples/terraform-packet/pharos-addons/packet-ccm/resources/03-clusterrolebinding.yml
  examples/terraform-packet/pharos-addons/packet-ccm/resources/04-deployment.yml
Labels: chore, documentation

#925 Tweak travis e2e
  .travis.yml
  e2e/travis.sh
Labels: chore

#926 Kubernetes v1.12.4
  lib/pharos_cluster.rb
Labels: bug, enhancement

#927 Improve ubuntu docker.io version pinning
  lib/pharos/host/ubuntu/scripts/configure-docker.sh
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
Labels: enhancement

#895 Drop "pharos build" alias for "pharos up"
  lib/pharos/root_command.rb
Labels: chore

#928 Prefix debug output with ssh hostname
  lib/pharos/ssh/client.rb
  lib/pharos/ssh/interactive_session.rb
  lib/pharos/ssh/remote_command.rb
  lib/pharos/ssh/remote_file.rb
  lib/pharos/ssh/tempfile.rb
Labels: enhancement

#905 Add build / installation documentation to README
  README.md
Labels: chore, documentation

#934 E2e: configure image registry
  e2e/cluster.yml
  e2e/digitalocean/cluster.yml
Labels: chore

#557 Initial Network LB addon implementation
  non-oss/pharos_pro/addons/kontena-network-lb/addon.rb
  non-oss/pharos_pro/addons/kontena-network-lb/resources/00-namespace.yml
  non-oss/pharos_pro/addons/kontena-network-lb/resources/01-controller-service-account.yml
  non-oss/pharos_pro/addons/kontena-network-lb/resources/02-controller-cluster-role.yml
  non-oss/pharos_pro/addons/kontena-network-lb/resources/03-speaker-service-account.yml
  non-oss/pharos_pro/addons/kontena-network-lb/resources/04-speaker-cluster-role.yml
  non-oss/pharos_pro/addons/kontena-network-lb/resources/05-config-watcher-role.yml
  non-oss/pharos_pro/addons/kontena-network-lb/resources/06-controller-cluster-role-binding.yml
  non-oss/pharos_pro/addons/kontena-network-lb/resources/07-speaker-cluster-role-binding.yml
  non-oss/pharos_pro/addons/kontena-network-lb/resources/08-config-watcher-role-binding.yml
  non-oss/pharos_pro/addons/kontena-network-lb/resources/20-speaker-daemonset.yml.erb
  non-oss/pharos_pro/addons/kontena-network-lb/resources/21-controller-deployment.yml.erb
  non-oss/spec/pharos_pro/addons/network_lb_spec.rb
Labels: enhancement
