Repository kontena/pharos-cluster, pull requests merged in 2018-09, with the labels that each got.

#583 Load also .yaml & .yaml.erb addon resource files
  lib/pharos/kube.rb
Labels: bug

#589 Use sudo for ip route
  lib/pharos/phases/gather_facts.rb
  spec/pharos/phases/gather_facts_spec.rb
Labels: bug

#591 Update cert-manager to 0.2.5
  addons/cert-manager/addon.rb
Labels: bug

#598 Kubernetes 1.11.3
  lib/pharos_cluster.rb
Labels: enhancement

#593 Don't abort when apt mark unhold reports nothing to unhold
  lib/pharos/host/ubuntu/scripts/configure-docker.sh
  lib/pharos/host/ubuntu/scripts/ensure-kubelet.sh
  lib/pharos/host/ubuntu/scripts/install-kube-packages.sh
Labels: bug

#599 cri-o 1.11.3
  lib/pharos_cluster.rb
Labels: enhancement

#605 Weave net 2.4.1
  lib/pharos/phases/configure_weave.rb
Labels: bug

#607 Improve addon config error message
  lib/pharos/addon_manager.rb
Labels: bug

#608 Fix el7 kubelet restart on upgrade
  lib/pharos/host/el7/scripts/ensure-kubelet.sh
  lib/pharos/host/el7/scripts/install-kube-packages.sh
Labels: bug

#621 Fix binary build temporary path
  build/drone/ubuntu_xenial.sh
Labels: bug

#619 Remove kured addon
  addons/kured/addon.rb
  addons/kured/resources/01-cluster-role.yml
  addons/kured/resources/02-service-account.yml
  addons/kured/resources/03-cluster-role-binding.yml
  addons/kured/resources/daemon-set.yml.erb
Labels: chore

#623 Rename OSS build packages
  build/drone/ubuntu_oss.sh
  build/travis/macos_oss.sh
Labels: chore

#626 Fix oss binary release step
  .drone.yml
Labels: bug, chore

#625 Refactor cluster version check to use Gem::Version && Gem::Requirement
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/validate_version.rb
  non-oss/phases/validate_version.rb
Labels: chore, enhancement

#567 Fix kube client host usage
  Gemfile.lock
  lib/pharos/addon_manager.rb
  lib/pharos/kube.rb
  lib/pharos/phases/configure_client.rb
  pharos-cluster.gemspec
  spec/pharos/kube_stack_spec.rb
Labels: bug

#615 Fix /etc/resolv.conf parser comment handling
  lib/pharos/autoload.rb
  lib/pharos/core-ext/ip_addr_loopback.rb
  lib/pharos/phases/gather_facts.rb
  lib/pharos/ssh/remote_file.rb
  spec/pharos/phases/gather_facts_spec.rb
Labels: bug

#631 Fix kubernetes dashboard addon first run timing issue
  addons/kubernetes-dashboard/addon.rb
Labels: bug

#632 Fix "undefined method cluster for Hash" in kubeclient
  lib/pharos/kube.rb
Labels: bug
