Repository kontena/pharos-cluster, pull requests merged in 2018-10, with the labels that each got.

#640 k8s-client 0.3.4
  Gemfile.lock
  pharos-cluster.gemspec
Labels: chore

#639 Fix 503 error in metrics-server setup
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/configure_metrics.rb
Labels: bug

#637 cri-o v1.11.6
  lib/pharos_cluster.rb
Labels: bug, chore

#635 Nested transform helpers to hashes and case conversions to strings
  lib/pharos/autoload.rb
  lib/pharos/config.rb
  lib/pharos/core-ext/deep_transform_keys.rb
  lib/pharos/core-ext/string_casing.rb
  lib/pharos/phases/store_cluster_configuration.rb
  spec/pharos/core_ext/deep_transform_keys_spec.rb
  spec/pharos/core_ext/string_casing_spec.rb
Labels: enhancement

#624 Enable EL7 docker repo on the fly
  lib/pharos/host/el7/centos7.rb
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/el7/rhel7.rb
  lib/pharos/host/el7/scripts/configure-docker.sh
Labels: enhancement

#641 Fix stack loading to ignore empty resources
  lib/pharos/kube.rb
  spec/fixtures/stacks/empty/empty.yml
  spec/fixtures/stacks/empty/test.yml
  spec/pharos/kube_stack_spec.rb
Labels: enhancement

#646 Addon: Helm
  addons/helm/addon.rb
  addons/helm/resources/01-service-account.yml
  addons/helm/resources/02-cluster-role-binding.yml
  addons/helm/resources/deployment.yml.erb
Labels: enhancement

#600 Kontena Storage addon
  .drone.yml
  .rubocop.yml
  non-oss/addons/kontena-storage/addon.rb
  non-oss/addons/kontena-storage/resources/00-namespace.yml
  non-oss/addons/kontena-storage/resources/01-cluster-crd.yml
  non-oss/addons/kontena-storage/resources/01-filesystem-crd.yml
  non-oss/addons/kontena-storage/resources/01-objectstore-crd.yml
  non-oss/addons/kontena-storage/resources/01-pool-crd.yml
  non-oss/addons/kontena-storage/resources/01-volume-crd.yml
  non-oss/addons/kontena-storage/resources/02-clusterrole.yml
  non-oss/addons/kontena-storage/resources/02-global-clusterrole.yml
  non-oss/addons/kontena-storage/resources/02-role.yml
  non-oss/addons/kontena-storage/resources/03-serviceaccount.yml
  non-oss/addons/kontena-storage/resources/04-clusterrolebinding.yml
  non-oss/addons/kontena-storage/resources/04-global-clusterrolebinding.yml
  non-oss/addons/kontena-storage/resources/04-rolebinding.yml
  non-oss/addons/kontena-storage/resources/05-deployment.yml.erb
  non-oss/addons/kontena-storage/resources/10-namespace.yml
  non-oss/addons/kontena-storage/resources/11-serviceaccount.yml
  non-oss/addons/kontena-storage/resources/12-role.yml
  non-oss/addons/kontena-storage/resources/13-mgmt-role-binding.yml
  non-oss/addons/kontena-storage/resources/14-rolebinding.yml
  non-oss/addons/kontena-storage/resources/15-cluster.yml.erb
  non-oss/addons/kontena-storage/resources/20-pool.yml
  non-oss/addons/kontena-storage/resources/21-storageclass.yml
  non-oss/addons/kontena-storage/resources/30-toolbox.yml.erb
  non-oss/spec/addons/kontena_storage_spec.rb
Labels: enhancement

#645 Add default worker label if none given by user
  lib/pharos/configuration/host.rb
  spec/pharos/configuration/host_spec.rb
Labels: enhancement

#648 Fix kontena-storage pool error
  non-oss/addons/kontena-storage/resources/20-pool.yml.erb
Labels: bug, chore

#654 Update cert-manager to 0.5.0
  addons/cert-manager/addon.rb
  addons/cert-manager/resources/cluster-role.yml
  addons/cert-manager/resources/deployment.yml.erb
  spec/pharos/addons/cert_manager_spec.rb
Labels: enhancement

#590 Run commands using --norc --noprofile
  lib/pharos/ssh/client.rb
  lib/pharos/ssh/remote_file.rb
Labels: bug

#652 Less strict systemd-generated resolv.conf detection
  lib/pharos/phases/gather_facts.rb
Labels: bug

#655 Switch to multi-arch compatible image registry
  addons/cert-manager/addon.rb
  addons/cert-manager/resources/deployment.yml.erb
  addons/helm/resources/deployment.yml.erb
  addons/host-upgrades/resources/50-daemonset.yml.erb
  addons/ingress-nginx/addon.rb
  addons/ingress-nginx/resources/daemonset.yml.erb
  addons/ingress-nginx/resources/default-backend.yml.erb
  addons/openebs/resources/10-api-server-deployment.yml.erb
  addons/openebs/resources/12-provisioner-deployment.yml.erb
  lib/pharos/addon.rb
  lib/pharos/config.rb
  lib/pharos/phases/configure_dns.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_telemetry.rb
  lib/pharos/phases/upgrade_master.rb
  lib/pharos/resources/metrics-server/metrics-server-deployment.yml.erb
  lib/pharos/resources/telemetry/cronjob.yml.erb
  lib/pharos/resources/weave/daemon-set.yml.erb
  lib/pharos/scripts/configure-etcd.sh
  lib/pharos/scripts/configure-kubelet-proxy.sh
  lib/pharos_cluster.rb
  spec/pharos/addon_spec.rb
  spec/pharos/addons/ingress_nginx_spec.rb
  spec/pharos/phases/configure_dns_spec.rb
  spec/pharos/phases/configure_kubelet_spec.rb
  spec/pharos/phases/upgrade_master_spec.rb
Labels: enhancement

#653 Pod security policies
  addons/ingress-nginx/resources/06-psp-role-binding.yml
  addons/openebs/resources/03-psp-role-binding.yml
  lib/pharos/cluster_manager.rb
  lib/pharos/config.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/pod_security_policy.rb
  lib/pharos/kubeadm.rb
  lib/pharos/phases/configure_psp.rb
  lib/pharos/resources/psp/00-privileged-psp.yml
  lib/pharos/resources/psp/01-privileged-role.yml
  lib/pharos/resources/psp/02-privileged-role-binding.yml
  lib/pharos/resources/psp/99-default-role-binding.yml
  lib/pharos/resources/psp/99-default-role.yml.erb
  lib/pharos/resources/psp/99-restricted-psp.yml
Labels: enhancement

#651 Add "environment:" host config to update /etc/environment
  cluster.example.yml
  lib/pharos/config_schema.rb
  lib/pharos/configuration/host.rb
  lib/pharos/host/configurer.rb
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/el7/scripts/configure-essentials.sh
  lib/pharos/host/ubuntu/scripts/configure-essentials.sh
  lib/pharos/host/ubuntu/ubuntu.rb
  lib/pharos/phases/configure_host.rb
  spec/pharos/host/configurer_spec.rb
Labels: enhancement

#660 Fix default pod security policy
  lib/pharos/configuration/pod_security_policy.rb
  lib/pharos/resources/psp/99-default-role-binding.yml
  non-oss/addons/kontena-storage/resources/02-clusterrole.yml
  non-oss/addons/kontena-storage/resources/02-global-clusterrole.yml
  non-oss/addons/kontena-storage/resources/12-role.yml
  non-oss/addons/kontena-storage/resources/30-toolbox.yml.erb
Labels: bug, chore

#661 Remove kubernetes-dashboard addon
  addons/kubernetes-dashboard/addon.rb
  addons/kubernetes-dashboard/resources/00-heapster-cluster-role.yml
  addons/kubernetes-dashboard/resources/01-heapster-service-account.yml
  addons/kubernetes-dashboard/resources/02-heapster-cluster-role-binding.yml
  addons/kubernetes-dashboard/resources/03-heapster-service.yml
  addons/kubernetes-dashboard/resources/04-heapster-deployment.yml.erb
  addons/kubernetes-dashboard/resources/configmap.yml
  addons/kubernetes-dashboard/resources/dashboard-admin-role-binding.yml
  addons/kubernetes-dashboard/resources/dashboard-admin-sa.yml
  addons/kubernetes-dashboard/resources/deployment.yml.erb
  addons/kubernetes-dashboard/resources/role-binding.yml
  addons/kubernetes-dashboard/resources/role.yml
  addons/kubernetes-dashboard/resources/secret-certs.yml
  addons/kubernetes-dashboard/resources/secret-key-holder.yml
  addons/kubernetes-dashboard/resources/service-account.yml
  addons/kubernetes-dashboard/resources/service.yml
Labels: chore

#664 Use cluster.yml dir as working dir for kubeconfig command
  lib/pharos/kubeconfig_command.rb
Labels: bug

#665 Allow to use custom docker runtime
  lib/pharos/config_schema.rb
  lib/pharos/configuration/host.rb
  lib/pharos/host/configurer.rb
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/el7/scripts/configure-docker.sh
  lib/pharos/host/ubuntu/scripts/configure-docker.sh
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
Labels: enhancement

#666 Upgrade kubeadm via configured repository
  lib/pharos/host/el7/scripts/upgrade-kubeadm.sh
  lib/pharos/host/ubuntu/scripts/upgrade-kubeadm.sh
  lib/pharos/host/ubuntu/ubuntu.rb
Labels: bug, enhancement

#603 Pharos version upgrade check
  lib/pharos/autoload.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/upgrade_check.rb
  pharos-cluster.gemspec
Labels: enhancement

#669 Add support for post install messages
  lib/pharos/addon.rb
  lib/pharos/addon_manager.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/up_command.rb
  spec/pharos/addon_spec.rb
Labels: enhancement

#647 Add support for enabling/disabling admission plugins
  lib/pharos/config.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/admission_plugin.rb
  lib/pharos/kubeadm.rb
  spec/pharos/config_spec.rb
  spec/pharos/kubeadm_spec.rb
Labels: enhancement

#673 fix cert manager resource order
  addons/cert-manager/resources/01-cluster-role.yml
  addons/cert-manager/resources/02-service-account.yml
  addons/cert-manager/resources/03-cluster-role-binding.yml
  addons/cert-manager/resources/10-certificate-crd.yml
  addons/cert-manager/resources/11-cluster-issuer-crd.yml
  addons/cert-manager/resources/12-issuer-crd.yml
  addons/cert-manager/resources/20-deployment.yml.erb
  addons/cert-manager/resources/21-issuer.yml.erb
Labels: bug

#627 Debian 9 support
  addons/host-upgrades/addon.rb
  lib/pharos/host/debian/debian.rb
  lib/pharos/host/debian/debian_stretch.rb
  lib/pharos/host/debian/scripts/configure-cfssl.sh
  lib/pharos/host/debian/scripts/configure-cri-o.sh
  lib/pharos/host/debian/scripts/configure-essentials.sh
  lib/pharos/host/debian/scripts/configure-netfilter.sh
  lib/pharos/host/debian/scripts/ensure-kubelet.sh
  lib/pharos/host/debian/scripts/install-kube-packages.sh
  lib/pharos/host/debian/scripts/repos/cri-o.sh
  lib/pharos/host/debian/scripts/repos/pharos_stretch.sh
  lib/pharos/host/debian/scripts/repos/update.sh
  lib/pharos/host/debian/scripts/reset.sh
  lib/pharos/host/debian/scripts/upgrade-kubeadm.sh
Labels: enhancement

#675 RHEL7: fix modprobe not found
  lib/pharos/host/el7/scripts/configure-netfilter.sh
Labels: bug, chore

#680 Install cri-o via package manager
  lib/pharos/host/debian/debian_stretch.rb
  lib/pharos/host/debian/scripts/configure-cri-o.sh
  lib/pharos/host/debian/scripts/repos/cri-o.sh
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/el7/scripts/configure-cri-o.sh
  lib/pharos/host/el7/scripts/repos/cri-o.sh
  lib/pharos/host/el7/scripts/reset.sh
  lib/pharos/host/ubuntu/scripts/configure-cri-o.sh
  lib/pharos/host/ubuntu/scripts/repos/cri-o.sh
  lib/pharos/host/ubuntu/scripts/reset.sh
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
Labels: enhancement

#672 Improve system pod qos/priorities
  lib/pharos/resources/calico/daemonset.yml.erb
  lib/pharos/resources/host-upgrades/daemonset.yml.erb
  lib/pharos/resources/metrics-server/metrics-server-deployment.yml.erb
  lib/pharos/resources/telemetry/cronjob.yml.erb
  lib/pharos/resources/weave/daemon-set.yml.erb
  lib/pharos/scripts/configure-etcd.sh
  lib/pharos/scripts/configure-kubelet-proxy.sh
Labels: enhancement

#682 Upgrade build environment bundler
  .drone.yml
Labels: chore

#576 Deprecate user addons directory in favor of pharos-addons
  lib/pharos/cluster_manager.rb
Labels: chore

#683 Add ssh_proxy_command option to hosts
  Gemfile.lock
  examples/vagrant/ubuntu/Vagrantfile
  examples/vagrant/ubuntu/block-ssh.sh
  lib/pharos/config_schema.rb
  lib/pharos/configuration/host.rb
  lib/pharos/ssh/manager.rb
  pharos-cluster.gemspec
Labels: enhancement

#685 Fix kontena-storage addon version
  non-oss/addons/kontena-storage/addon.rb
Labels: bug, chore

#681 Add "pharos license assign" command
  lib/pharos/autoload.rb
  lib/pharos/root_command.rb
  non-oss/addons/license-manager/addon.rb
  non-oss/addons/license-manager/resources/secret.yaml.erb
  non-oss/commands/license_assign_command.rb
  non-oss/commands/license_command.rb
  non-oss/spec/commands/license_assign_command_spec.rb
Labels: enhancement

#694 Kontena storage addon fixes
  non-oss/addons/kontena-storage/addon.rb
  non-oss/addons/kontena-storage/resources/05-deployment.yml.erb
  non-oss/addons/kontena-storage/resources/20-pool.yml.erb
  non-oss/addons/kontena-storage/resources/40-filesystem.yml.erb
  non-oss/addons/kontena-storage/resources/41-clusterrole.yml
  non-oss/addons/kontena-storage/resources/41-role.yml
  non-oss/addons/kontena-storage/resources/41-service-account.yml
  non-oss/addons/kontena-storage/resources/42-clusterrolebinding.yml
  non-oss/addons/kontena-storage/resources/42-rolebinding.yml
  non-oss/addons/kontena-storage/resources/43-deployment.yml.erb
  non-oss/addons/kontena-storage/resources/44-storageclass.yml.erb
Labels: bug

#695 Allow to update lens name
  non-oss/addons/kontena-lens/addon.rb
Labels: enhancement

#704 Fix version check to allow re-running up on prerelease versions
  lib/pharos/phases/validate_version.rb
  non-oss/spec/pharos_pro/phases/validate_version_spec.rb
  spec/pharos/phases/validate_version_spec.rb
Labels: bug

#700 Extract common command options to reusable modules
  lib/pharos/autoload.rb
  lib/pharos/command.rb
  lib/pharos/command_options/filtered_hosts.rb
  lib/pharos/command_options/load_config.rb
  lib/pharos/command_options/yes.rb
  lib/pharos/kubeconfig_command.rb
  lib/pharos/ssh_command.rb
  lib/pharos/up_command.rb
  spec/pharos/command_options/load_config_spec.rb
  spec/pharos/up_command_spec.rb
Labels: chore

#594 Run shellcheck for all shell scripts during automated tests
  .drone.yml
  build/drone/create_release.sh
  build/drone/ubuntu.sh
  build/drone/ubuntu_oss.sh
  build/travis/macos.sh
  build/travis/macos_oss.sh
  lib/pharos/host/debian/scripts/configure-cri-o.sh
  lib/pharos/host/debian/scripts/configure-essentials.sh
  lib/pharos/host/debian/scripts/ensure-kubelet.sh
  lib/pharos/host/debian/scripts/install-kube-packages.sh
  lib/pharos/host/debian/scripts/reset.sh
  lib/pharos/host/debian/scripts/upgrade-kubeadm.sh
  lib/pharos/host/el7/scripts/configure-cfssl.sh
  lib/pharos/host/el7/scripts/configure-cri-o.sh
  lib/pharos/host/el7/scripts/configure-docker.sh
  lib/pharos/host/el7/scripts/configure-essentials.sh
  lib/pharos/host/el7/scripts/ensure-kubelet.sh
  lib/pharos/host/el7/scripts/install-kube-packages.sh
  lib/pharos/host/el7/scripts/reset.sh
  lib/pharos/host/el7/scripts/upgrade-kubeadm.sh
  lib/pharos/host/ubuntu/scripts/configure-cri-o.sh
  lib/pharos/host/ubuntu/scripts/configure-docker.sh
  lib/pharos/host/ubuntu/scripts/configure-essentials.sh
  lib/pharos/host/ubuntu/scripts/ensure-kubelet.sh
  lib/pharos/host/ubuntu/scripts/install-kube-packages.sh
  lib/pharos/host/ubuntu/scripts/reset.sh
  lib/pharos/host/ubuntu/scripts/upgrade-kubeadm.sh
  lib/pharos/scripts/install-kubeadm.sh
  lib/pharos/scripts/kubeadm-init.sh
  lib/pharos/scripts/kubeadm-reconfigure.sh
  lib/pharos/scripts/pharos.sh
  lib/pharos/scripts/wait-etcd.sh
Labels: chore, enhancement

#707 Allow lens-operator to watch resources
  non-oss/pharos_pro/addons/kontena-lens/resources/lens-operator-cluster-access-role.yml
Labels: bug

#708 Update kontena license
  licenses/KONTENA.md
Labels: chore

#703 add support for configuring insecure registries through cluster.yml
  lib/pharos/config.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/container_runtime.rb
  lib/pharos/host/configurer.rb
  lib/pharos/host/debian/debian_stretch.rb
  lib/pharos/host/debian/scripts/configure-cri-o.sh
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/el7/scripts/configure-cri-o.sh
  lib/pharos/host/el7/scripts/configure-docker.sh
  lib/pharos/host/ubuntu/scripts/configure-cri-o.sh
  lib/pharos/host/ubuntu/scripts/configure-docker.sh
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
  lib/pharos/ssh/client.rb
  spec/pharos/host/configurer_spec.rb
  spec/pharos/host/ubuntu/ubuntu_xenial_spec.rb
Labels: enhancement

#711 Restore version back to 2.0.0-alpha.2
  lib/pharos/version.rb
  non-oss/spec/pharos_pro/commands/version_command_spec.rb
Labels: bug

#693 Improved PATH manipulation in el7/centos configure-essentials.sh
  lib/pharos/host/el7/scripts/configure-essentials.sh
Labels: bug

#712 Log waiting for etcd
  lib/pharos/phases/configure_etcd.rb
Labels: chore

#713 Warn when cluster version is going to change during "pharos up"
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/validate_version.rb
  lib/pharos/up_command.rb
  spec/pharos/up_command_spec.rb
Labels: enhancement

#721 Allow configuring of tolerations for ingress-nginx daemonset
  addons/ingress-nginx/addon.rb
  addons/ingress-nginx/resources/daemonset.yml.erb
Labels: enhancement

#725 update k8s-client to 0.4.2
  Gemfile.lock
  pharos-cluster.gemspec
  spec/pharos/kube_stack_spec.rb
Labels: enhancement

#722 Bump Lens version to 1.1.0
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement

#719 Bastion host
  Gemfile.lock
  lib/pharos/addon_manager.rb
  lib/pharos/config.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/bastion.rb
  lib/pharos/configuration/host.rb
  lib/pharos/kube.rb
  lib/pharos/phase.rb
  lib/pharos/ssh/client.rb
  lib/pharos/ssh/manager.rb
  lib/pharos/terraform/json_parser.rb
  pharos-cluster.gemspec
Labels: enhancement

#726 cri-o v1.11.7
  lib/pharos_cluster.rb
Labels: chore, enhancement

#727 Run the interactive ssh through Net::SSH
  lib/pharos/autoload.rb
  lib/pharos/ssh/client.rb
  lib/pharos/ssh/interactive_session.rb
  lib/pharos/ssh_command.rb
Labels: enhancement

#732 Kubernetes v1.11.4
  lib/pharos_cluster.rb
Labels: chore, enhancement

#705 Selectively reset a subset of hosts
  lib/pharos/cluster_manager.rb
  lib/pharos/command.rb
  lib/pharos/command_options/yes.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_client.rb
  lib/pharos/phases/delete_host.rb
  lib/pharos/phases/drain.rb
  lib/pharos/reset_command.rb
  lib/pharos/up_command.rb
  spec/pharos/up_command_spec.rb
Labels: enhancement

#739 Validate localhost dns resolve
  lib/pharos/phases/validate_host.rb
Labels: enhancement
