Repository kontena/pharos-cluster, pull requests merged in 2018-08, with the labels that each got.

#494 cri-o: add docker.io to default registries
  lib/pharos/host/el7/scripts/configure-cri-o.sh
  lib/pharos/host/ubuntu/scripts/configure-cri-o.sh
Labels: bug

#493 Kubernetes 1.10.6
  lib/pharos_cluster.rb
Labels: enhancement

#496 Restart docker on upgrade (ubuntu)
  lib/pharos/host/ubuntu/scripts/configure-docker.sh
Labels: bug

#455 Validate host routes
  lib/pharos/configuration/host.rb
  lib/pharos/configuration/network.rb
  lib/pharos/phases/gather_facts.rb
  lib/pharos/phases/validate_host.rb
  spec/pharos/configuration/host_route_spec.rb
  spec/pharos/configuration/host_spec.rb
  spec/pharos/phases/gather_facts_spec.rb
  spec/pharos/phases/validate_host_spec.rb
Labels: enhancement

#504 Fixup #455 for newer dry-struct
  lib/pharos/configuration/host.rb
  lib/pharos/configuration/network.rb
  spec/pharos/configuration/host_route_spec.rb
Labels: bug

#505 Change lscpu to uname -m
  lib/pharos/phases/gather_facts.rb
Labels: bug

#491 Update weave net to 2.4.0
  lib/pharos/phases/configure_weave.rb
  lib/pharos/resources/weave/01-cluster-role.yml
Labels: enhancement

#510 Fix pharos-cluster reset to use noninteractive debconf
  lib/pharos/host/ubuntu/scripts/reset.sh
Labels: bug

#511 Force LC_ALL=C.UTF-8 locale for all SSH commands
  lib/pharos/ssh/manager.rb
  lib/pharos/ssh/remote_command.rb
Labels: bug

#475 New K8s::Client
  addons/kubernetes-dashboard/addon.rb
  lib/pharos/addon.rb
  lib/pharos/autoload.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/kube.rb
  lib/pharos/kube/cert_manager.rb
  lib/pharos/kube/client.rb
  lib/pharos/kube/resource.rb
  lib/pharos/kube/session.rb
  lib/pharos/kube/stack.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_calico.rb
  lib/pharos/phases/configure_client.rb
  lib/pharos/phases/configure_dns.rb
  lib/pharos/phases/configure_metrics.rb
  lib/pharos/phases/configure_weave.rb
  lib/pharos/phases/label_node.rb
  lib/pharos/phases/store_cluster_configuration.rb
  lib/pharos/phases/upgrade_master.rb
  lib/pharos/up_command.rb
  pharos-cluster.gemspec
  spec/pharos/addon_spec.rb
  spec/pharos/kube/stack_spec.rb
  spec/pharos/kube_spec.rb
  spec/pharos/phases/configure_calico_spec.rb
  spec/pharos/phases/configure_dns_spec.rb
  spec/pharos/phases/label_node_spec.rb
  spec/pharos/phases/upgrade_master_spec.rb
Labels: enhancement

#516 Update k8s-client to 0.3.0
  pharos-cluster.gemspec
Labels: bug

#512 Retry phases (with exp backoff) on errors
  lib/pharos/phase.rb
  lib/pharos/phase_manager.rb
Labels: enhancement

#304 Use hostname for logging output
  lib/pharos/configuration/host.rb
  lib/pharos/phases/configure_etcd.rb
  spec/pharos/configuration/host_spec.rb
Labels: enhancement

#514 Ingress-nginx 0.17.1
  addons/ingress-nginx/addon.rb
  addons/ingress-nginx/resources/daemonset.yml.erb
Labels: enhancement

#520 Fix Pharos::Kube::Stack label/annotation override
  lib/pharos/kube.rb
  spec/fixtures/stacks/test/test.yml
  spec/pharos/kube_stack_spec.rb
Labels: bug

#522 Load libraries in phase manager to fix version command
  lib/pharos/phase_manager.rb
Labels: bug

#524 Update k8s-client to 0.3.1
  pharos-cluster.gemspec
Labels: bug

#527 Bump kubelet proxy version
  lib/pharos_cluster.rb
Labels: enhancement

#530 Lockdown crio stream-address to localhost-only for kubelet proxying
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
Labels: enhancement

#531 Add Gemfile.lock to version control for builds
  .gitignore
  Dockerfile
  Gemfile.lock
Labels: bug

#526 Update apiserver cert if SANs changed
  lib/pharos/phases/configure_master.rb
  lib/pharos/scripts/kubeadm-reconfigure.sh
Labels: enhancement

#528 Create release as a draft
  build/drone/create_release.sh
Labels: chore

#535 Don't upgrade kubelet, only ensure it's installed
  lib/pharos/host/el7/scripts/ensure-kubelet.sh
  lib/pharos/host/ubuntu/scripts/ensure-kubelet.sh
Labels: bug

#502 Add pharos-cluster kubeconfig -command
  lib/pharos/kube.rb
  lib/pharos/kube/config.rb
  lib/pharos/kubeconfig_command.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_client.rb
  lib/pharos/reset_command.rb
  lib/pharos/root_command.rb
  lib/pharos/up_command.rb
Labels: enhancement

#539 Downgrade cri-o to 1.11.0
  lib/pharos_cluster.rb
Labels: bug

#544 Fix kubeconfig command SSH client call
  lib/pharos/kubeconfig_command.rb
Labels: bug

#537 Normalize help description casings
  lib/pharos/command.rb
  lib/pharos/root_command.rb
  lib/pharos/up_command.rb
Labels: chore

#545 Upgrade k8s-client version 0.3.2
  Gemfile.lock
  pharos-cluster.gemspec
Labels: bug

#536 Add telemetry
  lib/pharos/cluster_manager.rb
  lib/pharos/config.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/telemetry.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_telemetry.rb
  lib/pharos/resources/telemetry/01-cluster-role.yml
  lib/pharos/resources/telemetry/02-service-account.yml
  lib/pharos/resources/telemetry/03-role.yml
  lib/pharos/resources/telemetry/04-role-binding.yml
  lib/pharos/resources/telemetry/05-cluster-role-binding.yml
  lib/pharos/resources/telemetry/cronjob.yml.erb
Labels: enhancement

#546 Improve kubeconfig hint
  lib/pharos/kube.rb
  lib/pharos/kubeconfig_command.rb
  lib/pharos/up_command.rb
Labels: enhancement

#550 cri-o 1.11.2
  lib/pharos_cluster.rb
Labels: bug

#548 Fix kube client config
  lib/pharos/addon.rb
  lib/pharos/addon_manager.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/kube.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_client.rb
  lib/pharos/phases/load_cluster_configuration.rb
  spec/pharos/addon_spec.rb
  spec/pharos/addons/host_upgrades_spec.rb
  spec/pharos/addons/ingress_nginx_spec.rb
  spec/pharos/addons/openebs_spec.rb
Labels: bug

#552 Basename instead of full path in post-install command example
  lib/pharos/up_command.rb
Labels: chore

#554 Add chpharos token to telemetry
  lib/pharos/phases/configure_telemetry.rb
  lib/pharos/resources/telemetry/06-secret.yml.erb
  lib/pharos/resources/telemetry/cronjob.yml.erb
  spec/pharos/phases/configure_telemetry_spec.rb
Labels: enhancement

#561 Patch coredns image only on arm64
  lib/pharos/phases/configure_dns.rb
  lib/pharos/phases/upgrade_master.rb
  spec/pharos/phases/configure_dns_spec.rb
Labels: enhancement

#572 Fix apiserver & controller-manager cloud-provider args
  lib/pharos/kubeadm.rb
  spec/pharos/kubeadm_spec.rb
Labels: bug

#569 Use the real program name in help and version output
  lib/pharos/command.rb
  lib/pharos/root_command.rb
  lib/pharos/version_command.rb
Labels: bug

#574 Fix telemetry cronjob
  lib/pharos/resources/telemetry/cronjob.yml.erb
Labels: bug, chore

#575 Update conformance docs
  conformance/README.md
Labels: chore, documentation

#578 Add missing kubeadm-flags.env on upgrade
  lib/pharos/phases/migrate_worker.rb
Labels: bug
