Repository kontena/pharos-cluster, pull requests merged in 2018-11, with the labels that each got.

#754 Raise UnknownAddon error earlier if add-on class not found
  lib/pharos/addon_manager.rb
Labels: enhancement

#751 Upgrade Kontena Lens to version 1.2.0
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement

#750 Enhance lens-authenticator manifest
  non-oss/pharos_pro/addons/kontena-lens/resources/06-authenticator-daemonset.yml.erb
Labels: bug

#748 Retry if lens configuration creation fails
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement

#755 Don't validate cluster version if api down
  lib/pharos/phases/validate_version.rb
Labels: bug, enhancement

#749 Downgrade cri-o to 1.11.6
  lib/pharos/cluster_manager.rb
  lib/pharos/config.rb
  lib/pharos/configuration/host.rb
  lib/pharos/host/configurer.rb
  lib/pharos/host/debian/debian_stretch.rb
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/el7/scripts/configure-cri-o.sh
  lib/pharos/host/el7/scripts/configure-essentials.sh
  lib/pharos/host/ubuntu/scripts/configure-cri-o.sh
  lib/pharos/host/ubuntu/ubuntu.rb
  lib/pharos/kubeconfig_command.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_host.rb
  lib/pharos/reset_command.rb
  lib/pharos/ssh/manager.rb
  lib/pharos/ssh_command.rb
  lib/pharos_cluster.rb
  non-oss/pharos_pro/phases/configure_host.rb
Labels: bug, enhancement

#758 Update digitalocean example to 2.0
  examples/terraform-do/cluster.yml
Labels: chore

#759 Update terraform-aws example
  examples/terraform-aws/cluster.yml
Labels: chore

#760 Fix ubuntu configurer error when docker is used
  lib/pharos/host/ubuntu/ubuntu.rb
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
Labels: bug, chore

#764 Fix el7 kubeadm upgrade download
  lib/pharos/host/el7/scripts/upgrade-kubeadm.sh
Labels: bug

#767 Telemetry 0.2.0
  lib/pharos_cluster.rb
Labels: chore, enhancement

#766 Enable RHEL 7.6
  lib/pharos/host/el7/rhel7.rb
Labels: chore, enhancement

#769 Fix version upgrade warning message typo
  lib/pharos/up_command.rb
Labels: chore

#753 Fix kubeconfig post install hint arguments
  lib/pharos/up_command.rb
Labels: bug

#762 Add --force to "pharos up" to force upgrade from an unsupported version
  lib/pharos/phases/validate_version.rb
  lib/pharos/up_command.rb
  spec/pharos/phases/validate_version_spec.rb
  spec/pharos/up_command_spec.rb
Labels: enhancement

#765 Fix upgrade from previous versions
  lib/pharos/phases/configure_master.rb
  lib/pharos/phases/upgrade_master.rb
Labels: bug, enhancement

#776 Release v2.0.0
  lib/pharos/version.rb
Labels: enhancement

#778 More compatible localhost hostname validation
  lib/pharos/phases/validate_host.rb
Labels: bug

#771 Remove -d --debug -f --force from kubeconfig hint
  lib/pharos/up_command.rb
Labels: bug

#779 Fix kontena-storage device_filter
  non-oss/pharos_pro/addons/kontena-storage/addon.rb
Labels: bug

#783 Fix etcd_version_matches
  lib/pharos/scripts/configure-etcd.sh
Labels: bug

#784 Allow to use Kontena Lens with custom host without tls option
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/12-ingress.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/13-certificate.yml.erb
Labels: bug

#793 Add issue and feature request templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: chore

#790 Fix cert-manager crash on issuer migration
  addons/cert-manager/addon.rb
Labels: bug

#795 Ingress-nginx: dynamic upstream config changes
  addons/ingress-nginx/resources/daemonset.yml.erb
Labels: bug

#800 cri-o v1.11.9
  lib/pharos_cluster.rb
Labels: bug

#792 Don't dump backtrace in pharos ssh when no hosts defined
  lib/pharos/command.rb
  lib/pharos/reset_command.rb
  lib/pharos/root_command.rb
  lib/pharos/ssh_command.rb
  lib/pharos/up_command.rb
Labels: bug

#804 Fix rhel version check
  lib/pharos/host/configurer.rb
  spec/pharos/configuration/host_spec.rb
  spec/pharos/host/configurer_spec.rb
Labels: bug

#810 Fix ingress-nginx default worker-shutdown-timeout
  addons/ingress-nginx/addon.rb
Labels: bug

#812 Use full hostname on vsphere
  lib/pharos/phases/gather_facts.rb
  spec/pharos/phases/gather_facts_spec.rb
Labels: bug

#808 Fix kontena-lens create-config success check
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: bug

#801 Update ubuntu bionic docker to v18.06.1
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
Labels: enhancement

#822 Store kontena-lens config directly to the k8s api
  Gemfile.lock
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  pharos-cluster.gemspec
Labels: enhancement

#827 Bundle an up-to-date cacert.pem file into binary during build
  bin/pharos-cluster
  build/drone/ubuntu.sh
  build/drone/ubuntu_oss.sh
  build/travis/macos.sh
  build/travis/macos_oss.sh
  pharos-cluster.gemspec
Labels: bug

#798 Remove Pharos::SSH::Manager in favor of simpler host.ssh accessor
  lib/pharos/autoload.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/config.rb
  lib/pharos/configuration/host.rb
  lib/pharos/kubeconfig_command.rb
  lib/pharos/phase.rb
  lib/pharos/phase_manager.rb
  lib/pharos/phases/configure_bootstrap.rb
  lib/pharos/phases/configure_cfssl.rb
  lib/pharos/phases/configure_client.rb
  lib/pharos/phases/configure_etcd.rb
  lib/pharos/phases/configure_etcd_ca.rb
  lib/pharos/phases/configure_etcd_changes.rb
  lib/pharos/phases/configure_host.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_master.rb
  lib/pharos/phases/configure_secrets_encryption.rb
  lib/pharos/phases/gather_facts.rb
  lib/pharos/phases/join_node.rb
  lib/pharos/phases/setup_master.rb
  lib/pharos/phases/upgrade_master.rb
  lib/pharos/phases/validate_host.rb
  lib/pharos/phases/validate_version.rb
  lib/pharos/reset_command.rb
  lib/pharos/ssh/manager.rb
  lib/pharos/ssh_command.rb
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/commands/license_assign_command.rb
  non-oss/pharos_pro/phases/configure_host.rb
  non-oss/spec/pharos_pro/phases/validate_version_spec.rb
  spec/pharos/host/configurer_spec.rb
  spec/pharos/kubeadm_spec.rb
  spec/pharos/phases/configure_encryption_secrets_spec.rb
  spec/pharos/phases/configure_kubelet_spec.rb
  spec/pharos/phases/configure_telemetry_spec.rb
  spec/pharos/phases/gather_facts_spec.rb
  spec/pharos/phases/join_node_spec.rb
  spec/pharos/phases/migrate_master_spec.rb
  spec/pharos/phases/migrate_worker_spec.rb
  spec/pharos/phases/validate_host_spec.rb
  spec/pharos/phases/validate_version_spec.rb
Labels: chore, enhancement

#830 Fix --help
  lib/pharos/command.rb
Labels: bug

#818 Fix multi-arch clusters
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/configure_kube_proxy.rb
Labels: bug

#833 Fix missing data directory during build
  build/drone/ubuntu.sh
  build/drone/ubuntu_oss.sh
  build/travis/macos.sh
  build/travis/macos_oss.sh
Labels: chore

#832 Pharos::Command specs
  lib/pharos/command.rb
  spec/pharos/command_spec.rb
  spec/spec_helper.rb
  spec/support/exit_with_error_helper.rb
Labels: chore

#826 Improve reset logic
  addons/openebs/addon.rb
  lib/pharos/addon.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/delete_host.rb
  lib/pharos/phases/drain.rb
  lib/pharos/reset_command.rb
  lib/pharos/ssh/client.rb
  non-oss/pharos_pro/addons/kontena-storage/addon.rb
  spec/pharos/cluster_manager_spec.rb
Labels: bug, enhancement

#820 Cert-manager v0.5.2
  addons/cert-manager/addon.rb
Labels: bug

#835 Kubernetes v1.12.2
  lib/pharos/cluster_manager.rb
  lib/pharos/configuration/host.rb
  lib/pharos/phases/configure_kube_proxy.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/upgrade_master.rb
  lib/pharos_cluster.rb
Labels: enhancement

#821 Weave Net v2.5.0
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_weave.rb
Labels: enhancement

#836 Bump version to v2.1.0-alpha.0
  lib/pharos/version.rb
Labels: chore

#838 k8s-client v0.6.1
  Gemfile.lock
Labels: bug

#837 Remove the bundled SSL cert that did not get used
  bin/pharos-cluster
  build/drone/ubuntu.sh
  build/drone/ubuntu_oss.sh
  build/travis/macos.sh
  build/travis/macos_oss.sh
  pharos-cluster.gemspec
Labels: chore

#839 Update build scripts for rubyc 0.5 + ruby 2.5
  .drone.yml
  .rubocop.yml
  .travis.yml
  build/drone/ubuntu.sh
  build/drone/ubuntu_oss.sh
  build/travis/macos.sh
  build/travis/macos_oss.sh
  lib/pharos/cluster_manager.rb
  lib/pharos/command_options/load_config.rb
  lib/pharos/phases/gather_facts.rb
  lib/pharos/ssh_command.rb
Labels: bug, chore

#840 Travis e2e
  .travis.yml
  README.md
  e2e/cluster.yml
  e2e/travis.sh
  lib/pharos/cluster_manager.rb
Labels: chore

#797 Randomize test case run order
  .rspec
  spec/pharos/phases/configure_kubelet_spec.rb
  spec/pharos/phases/configure_telemetry_spec.rb
  spec/spec_helper.rb
Labels: chore

#816 Validate cluster.yml address format
  lib/pharos/config_schema.rb
  spec/pharos/config_spec.rb
Labels: enhancement

#845 Use fixed ruby-packer with working openssl-dir arg
  build/drone/ubuntu.sh
  build/drone/ubuntu_oss.sh
  build/travis/macos.sh
  build/travis/macos_oss.sh
Labels: bug

#846 k8s-client 0.6.3
  Gemfile.lock
  pharos-cluster.gemspec
Labels: chore

#796 Add Lens tls.enabled option
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/12-ingress.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/13-certificate.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/14-issuer.yml.erb
Labels: enhancement

#849 metrics-server v0.3.1
  lib/pharos/phases/configure_metrics.rb
  lib/pharos/resources/metrics-server/metrics-server-deployment.yml.erb
Labels: enhancement

#852 Transfer host environment variables from Terraform output
  lib/pharos/terraform/json_parser.rb
Labels: bug

#851 Set NO_PROXY into container runtime config
  lib/pharos/host/debian/scripts/configure-cri-o.sh
  lib/pharos/host/debian/scripts/configure-docker.sh
  lib/pharos/host/el7/scripts/configure-cri-o.sh
  lib/pharos/host/el7/scripts/configure-docker.sh
  lib/pharos/host/ubuntu/scripts/configure-cri-o.sh
  lib/pharos/host/ubuntu/scripts/configure-docker.sh
  lib/pharos/scripts/pharos.sh
  lib/pharos/ssh/client.rb
Labels: bug

#768 Region aware peer addresses
  lib/pharos/cluster_manager.rb
  lib/pharos/config.rb
  lib/pharos/configuration/host.rb
  lib/pharos/kubeadm.rb
  lib/pharos/phases/configure_etcd.rb
  lib/pharos/phases/configure_etcd_changes.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/configure_weave.rb
  lib/pharos/phases/label_node.rb
  lib/pharos/phases/validate_host.rb
  lib/pharos/resources/weave/daemon-set.yml.erb
  spec/pharos/config_spec.rb
  spec/pharos/configuration/host_spec.rb
  spec/pharos/phases/label_node_spec.rb
Labels: enhancement
