Repository kontena/pharos-cluster, pull requests merged in 2018-06, with the labels that each got.

#395 Unset http_proxy envs before executing kubeadm
  lib/pharos/phases/configure_master.rb
  lib/pharos/scripts/kubeadm-init.sh
  lib/pharos/scripts/kubeadm-reconfigure.sh
  lib/pharos/scripts/pharos.sh
Labels: bug

#396 Upgrade ingress-nginx to 0.15.0
  addons/ingress-nginx/addon.rb
Labels: enhancement

#401 Fix SetupMaster and ClusterManager for optional configuration cases
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/setup_master.rb
Labels: bug

#403 Ensure that /etc/apt/apt.conf.d/20auto-upgrades exist
  lib/pharos/scripts/configure-essentials.sh
Labels: bug, chore

#408 Conformance testing instructions
  conformance/README.md
Labels: chore, documentation

#411 Update rubocop to 0.57
  lib/pharos/config.rb
  lib/pharos/configuration/api.rb
  lib/pharos/configuration/audit.rb
  lib/pharos/logging.rb
  pharos-cluster.gemspec
Labels: chore

#412 Upgrade net-ssh dependency to 5.0.1
  pharos-cluster.gemspec
Labels: chore

#362 Host operating system configurers
  lib/pharos/autoload.rb
  lib/pharos/configuration/host.rb
  lib/pharos/configuration/os_release.rb
  lib/pharos/host/configurer.rb
  lib/pharos/host/ubuntu/scripts/configure-cfssl.sh
  lib/pharos/host/ubuntu/scripts/configure-cri-o.sh
  lib/pharos/host/ubuntu/scripts/configure-docker.sh
  lib/pharos/host/ubuntu/scripts/configure-essentials.sh
  lib/pharos/host/ubuntu/scripts/configure-netfilter.sh
  lib/pharos/host/ubuntu/scripts/ensure-kubelet.sh
  lib/pharos/host/ubuntu/scripts/install-kubelet.sh
  lib/pharos/host/ubuntu/scripts/repos/cri-o.sh
  lib/pharos/host/ubuntu/scripts/repos/pharos_bionic.sh
  lib/pharos/host/ubuntu/scripts/repos/pharos_xenial.sh
  lib/pharos/host/ubuntu/scripts/repos/update.sh
  lib/pharos/host/ubuntu/scripts/upgrade-kubeadm.sh
  lib/pharos/host/ubuntu/ubuntu.rb
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
  lib/pharos/host_config_manager.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_cfssl.rb
  lib/pharos/phases/configure_etcd.rb
  lib/pharos/phases/configure_host.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/upgrade_master.rb
  lib/pharos/phases/validate_host.rb
  lib/pharos/scripts/configure-etcd.sh
  lib/pharos/scripts/configure-kube.sh
  lib/pharos/scripts/configure-kubelet-proxy.sh
  lib/pharos/scripts/wait-etcd.sh
  lib/pharos/scripts/wait-kubelet-proxy.sh
  spec/pharos/configuration/host_spec.rb
  spec/pharos/configuration/os_release_spec.rb
  spec/pharos/host/configurer_spec.rb
Labels: enhancement

#423 Fix global --version etc to work in the root command level
  lib/pharos/root_command.rb
Labels: bug

#424 Handle migration from 1.1.x to 1.2.x
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/migrate_master.rb
  lib/pharos/phases/migrate_worker.rb
  lib/pharos/scripts/wait-kubelet-proxy.sh
  lib/pharos/ssh/remote_file.rb
  spec/pharos/phases/migrate_master_spec.rb
  spec/pharos/phases/migrate_worker_spec.rb
Labels: bug

#425 Fix centos/rhel7 essentials
  lib/pharos/host/el7/scripts/configure-docker.sh
  lib/pharos/host/el7/scripts/configure-essentials.sh
Labels: bug, chore

#430 Fix ubuntu xenial cri-o error
  lib/pharos/cluster_manager.rb
  lib/pharos/configuration/host.rb
  lib/pharos/host/configurer.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
  lib/pharos/host_config_manager.rb
  lib/pharos/phases/validate_host.rb
  lib/pharos/version_command.rb
  spec/pharos/configuration/host_spec.rb
  spec/pharos/host/configurer_spec.rb
  spec/pharos/host/ubuntu/ubuntu_xenial_spec.rb
Labels: bug

#437 Cleanup vagrant folder structure
  examples/vagrant/centos7/Vagrantfile
  examples/vagrant/ubuntu/README.md
  examples/vagrant/ubuntu/Vagrantfile
  examples/vagrant/ubuntu/cluster-external-etcd.yml
  examples/vagrant/ubuntu/cluster.yml
  examples/vagrant/ubuntu/etcd_certs/ca-config.json
  examples/vagrant/ubuntu/etcd_certs/ca-csr.json
  examples/vagrant/ubuntu/etcd_certs/ca-key.pem
  examples/vagrant/ubuntu/etcd_certs/ca.csr
  examples/vagrant/ubuntu/etcd_certs/ca.pem
  examples/vagrant/ubuntu/etcd_certs/client-key.pem
  examples/vagrant/ubuntu/etcd_certs/client.csr
  examples/vagrant/ubuntu/etcd_certs/client.json
  examples/vagrant/ubuntu/etcd_certs/client.pem
  examples/vagrant/ubuntu/etcd_certs/config.json
  examples/vagrant/ubuntu/etcd_certs/server-key.pem
  examples/vagrant/ubuntu/etcd_certs/server.csr
  examples/vagrant/ubuntu/etcd_certs/server.pem
  examples/vagrant/ubuntu/proxy-only.sh
Labels: chore

#393 Update host-upgrades addon to use pharos-host-upgrades
  addons/host-upgrades/addon.rb
  addons/host-upgrades/resources/10-clusterrole.yml
  addons/host-upgrades/resources/20-serviceaccount.yml
  addons/host-upgrades/resources/30-clusterrolebinding.yml
  addons/host-upgrades/resources/40-configmap.yml
  addons/host-upgrades/resources/50-daemonset.yml.erb
  addons/host-upgrades/resources/daemonset.yml.erb
  lib/pharos/addon.rb
  pharos-cluster.gemspec
  spec/pharos/addons/host_upgrades_spec.rb
Labels: enhancement

#442 Show deprecation notice in kured output
  addons/kured/addon.rb
Labels: bug, chore

#436 Fix output error when color is disabled
  lib/pharos/command.rb
  lib/pharos/up_command.rb
  spec/pharos/up_command_spec.rb
Labels: bug

#445 Update Calico to v3.1.3
  lib/pharos/phases/configure_calico.rb
Labels: enhancement

#447 rubocop: forget about Lint/SplatKeywordArguments
  .rubocop.yml
Labels: chore

#444 Don't add --node-ip if cloud.provider is set
  lib/pharos/configuration/host.rb
  lib/pharos/phases/configure_kubelet.rb
  spec/pharos/phases/configure_kubelet_spec.rb
Labels: bug

#450 Detect systemd-resolved stub resolver at localhost and bypass using kubelet --resolv-conf
  lib/pharos/autoload.rb
  lib/pharos/configuration/host.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/validate_host.rb
  lib/pharos/ssh/remote_file.rb
  spec/pharos/phases/configure_kubelet_spec.rb
  spec/pharos/phases/validate_host_spec.rb
Labels: bug

#454 Validate calico ippool cidr against the cluster.yml pod network cidr
  lib/pharos/phases/configure_calico.rb
  spec/pharos/phases/configure_calico_spec.rb
Labels: enhancement

#432 Cluster reset command
  lib/pharos/cluster_manager.rb
  lib/pharos/host/configurer.rb
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/el7/scripts/reset.sh
  lib/pharos/host/ubuntu/scripts/reset.sh
  lib/pharos/host/ubuntu/ubuntu.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
  lib/pharos/phases/gather_facts.rb
  lib/pharos/phases/reset_host.rb
  lib/pharos/phases/validate_host.rb
  lib/pharos/phases/validate_hostname.rb
  lib/pharos/reset_command.rb
  lib/pharos/root_command.rb
  spec/pharos/phases/gather_facts_spec.rb
  spec/pharos/phases/validate_host_spec.rb
  spec/pharos/phases/validate_hostname_spec.rb
Labels: enhancement

#457 Don't set default value for ssh user
  lib/pharos/configuration/host.rb
Labels: bug

#456 Update cri-o to v1.10.4
  lib/pharos_cluster.rb
Labels: chore, enhancement

#460 Enable kubelet authentication token webhook
  lib/pharos/phases/configure_kubelet.rb
  spec/pharos/phases/configure_kubelet_spec.rb
Labels: bug

#461 Replace heapster with metrics-server
  addons/kubernetes-dashboard/addon.rb
  addons/kubernetes-dashboard/resources/00-heapster-cluster-role.yml
  addons/kubernetes-dashboard/resources/01-heapster-service-account.yml
  addons/kubernetes-dashboard/resources/02-heapster-cluster-role-binding.yml
  addons/kubernetes-dashboard/resources/03-heapster-service.yml
  addons/kubernetes-dashboard/resources/04-heapster-deployment.yml.erb
  lib/pharos/kube.rb
  lib/pharos/kubeadm.rb
  lib/pharos/phases/configure_metrics.rb
  lib/pharos/resources/heapster/configmap.yml.erb
  lib/pharos/resources/heapster/deployment.yml.erb
  lib/pharos/resources/metrics-server/configmap.yml.erb
  lib/pharos/resources/metrics-server/metrics-server-deployment.yml.erb
Labels: enhancement

#462 Refresh yum repo metadata on every run
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/el7/scripts/repos/update.sh
Labels: bug, chore

#464 add cluster-service annotation to dashboard
  addons/kubernetes-dashboard/addon.rb
  addons/kubernetes-dashboard/resources/service.yml
Labels: bug
