Repository kontena/pharos-cluster, pull requests merged in 2019-01, with the labels that each got.

#931 create cluster issuer with kube CA
  addons/cert-manager/addon.rb
Labels: enhancement

#942 Fix travis bundler error
  .travis.yml
Labels: chore

#854 Remove exponential backoff from retries
  lib/pharos/addon_manager.rb
  lib/pharos/autoload.rb
  lib/pharos/phase_manager.rb
  lib/pharos/phases/configure_metrics.rb
  lib/pharos/retry.rb
Labels: enhancement

#943 k8s-client v0.7.0
  Gemfile.lock
  pharos-cluster.gemspec
Labels: bug

#911 Improve SSH password / passphrase prompting
  lib/pharos/cluster_manager.rb
  lib/pharos/configuration/host.rb
  lib/pharos/host/configurer.rb
  lib/pharos/phases/authenticate_ssh.rb
  lib/pharos/phases/connect_ssh.rb
  lib/pharos/ssh/client.rb
  spec/pharos/host/configurer_spec.rb
Labels: bug, enhancement

#944 Update rubyc to v0.5.0+extra5
  build/drone/ubuntu.sh
  build/drone/ubuntu_oss.sh
  build/travis/macos.sh
  build/travis/macos_oss.sh
Labels: chore

#947 Fix erb trim mode warning
  lib/pharos/yaml_file.rb
Labels: bug, chore

#952 Remove bundler version restriction
  pharos-cluster.gemspec
Labels: chore

#951 Fix k8s api connection via bastion host
  lib/pharos/config.rb
  spec/pharos/config_spec.rb
Labels: bug

#954 Silence phase thread exception reporting
  lib/pharos/phase_manager.rb
Labels: bug, chore

#955 k8s-client v0.8.0
  Gemfile.lock
  pharos-cluster.gemspec
Labels: bug, enhancement

#948 Calico v3.2.4
  lib/pharos/phases/configure_calico.rb
  lib/pharos/resources/calico/10-cluster-role.yml
Labels: enhancement

#959 Fix calico daemonset probes
  lib/pharos/resources/calico/daemonset.yml.erb
Labels: bug

#968 Update Kontena Lens to version 1.4.0-alpha.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/15-helm-api-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/15-helm-api-service.yml
  non-oss/pharos_pro/addons/kontena-lens/resources/16-k8s-resource-applier-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/16-k8s-resource-applier-service.yml
  non-oss/pharos_pro/addons/kontena-lens/resources/cluster_crd.yml
Labels: enhancement

#970 Disable travis homebrew update
  build/travis/macos.sh
  build/travis/macos_oss.sh
Labels: chore

#972 K8s-client v0.8.1
  Gemfile.lock
  pharos-cluster.gemspec
Labels: bug, chore

#976 Remove unix:// prefix from container-runtime-endpoint
  lib/pharos/configuration/host.rb
Labels: bug

#973 Fix to reset of openebs plugin
  addons/openebs/addon.rb
Labels: bug

#974 Add nat_outgoing to network config.
  lib/pharos/configuration/network.rb
  lib/pharos/phases/configure_calico.rb
Labels: bug

#979 host upgrades addon v0.3.1
  addons/host-upgrades/addon.rb
Labels: bug

#982 Update rubyc to 2.6.0-0.6.0
  build/drone/ubuntu.sh
  build/drone/ubuntu_oss.sh
  build/travis/macos.sh
  build/travis/macos_oss.sh
Labels: chore

#980 Kubernetes v1.13.2
  lib/pharos_cluster.rb
Labels: bug, enhancement

#981 Fix kontena-lens resource applier cpu request
  non-oss/pharos_pro/addons/kontena-lens/resources/16-k8s-resource-applier-deployment.yml.erb
Labels: bug, chore, pro

#828 Add config option to pass skip_refresh option to shell image
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/07-dashboard-deployment.yml.erb
Labels: bug

#985 Fix Ubuntu Bionic cri-o cgroup driver fallback logic
  lib/pharos/host/configurer.rb
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
  spec/pharos/host/configurer_spec.rb
  spec/pharos/host/ubuntu/ubuntu_xenial_spec.rb
Labels: bug

#989 Fix loading of addons from symlinked directories under pharos-addons/
  lib/pharos/addon_manager.rb
  spec/pharos/addon_manager_spec.rb
Labels: bug, enhancement

#990 Place kontena-lens redis to a master node
  non-oss/pharos_pro/addons/kontena-lens/resources/10-redis-deployment.yml.erb
Labels: enhancement, pro

#994 Update Kontena Lens to version 1.4.0-beta.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/15-helm-api-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/15-helm-api-pvc.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/17-lens-helm-tiller-namespace.yml
  non-oss/pharos_pro/addons/kontena-lens/resources/17-lens-helm-tiller-sa.yml
  non-oss/pharos_pro/addons/kontena-lens/resources/18-helm-lens-tiller-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/18-lens-helm-tiller-binding.yml
  non-oss/pharos_pro/addons/kontena-lens/resources/18-lens-helm-user-role.yml
Labels: enhancement

#1001 Generate helm_repositories string properly
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: bug

#1002 Change helm-api to StatefulSet
  non-oss/pharos_pro/addons/kontena-lens/resources/15-helm-api-statefulset.yml.erb
Labels: enhancement

#1000 Pull control plane images parallel
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/pull_master_images.rb
Labels: enhancement

#1006 Improve kontena-lens addon installation flow
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/04-user-management-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/05-user-management-service.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/06-authenticator-daemonset.yml.erb
Labels: enhancement

#992 Protect (firewall) cluster using firewalld
  lib/pharos/cluster_manager.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/network.rb
  lib/pharos/host/configurer.rb
  lib/pharos/host/debian/debian.rb
  lib/pharos/host/debian/scripts/configure-essentials.sh
  lib/pharos/host/debian/scripts/configure-firewalld.sh
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/el7/scripts/configure-essentials.sh
  lib/pharos/host/el7/scripts/configure-firewalld.sh
  lib/pharos/host/ubuntu/scripts/configure-firewalld.sh
  lib/pharos/host/ubuntu/ubuntu.rb
  lib/pharos/phases/configure_calico.rb
  lib/pharos/phases/configure_firewalld.rb
  lib/pharos/phases/configure_weave.rb
  lib/pharos/resources/calico/daemonset.yml.erb
  lib/pharos/resources/firewalld/ipset.xml.erb
  lib/pharos/resources/firewalld/service.xml.erb
  lib/pharos/resources/weave/daemon-set.yml.erb
  lib/pharos/scripts/configure-firewalld.sh
  lib/pharos/scripts/disable-firewalld.sh
Labels: enhancement

#1007 Increase Helm API memory limit
  non-oss/pharos_pro/addons/kontena-lens/resources/15-helm-api-statefulset.yml.erb
Labels: bug

#1005 Fix nested addon configuration validation errors
  lib/pharos/addon_manager.rb
  spec/pharos/addon_manager_spec.rb
Labels: bug

#1009 Update Kontena Lens to version 1.4.0-rc.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement

#1012 Add charts.enabled configuration option for Kontena Lens
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/07-dashboard-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/15-helm-api-pvc.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/15-helm-api-service.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/15-helm-api-statefulset.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/17-lens-helm-tiller-namespace.yml
  non-oss/pharos_pro/addons/kontena-lens/resources/17-lens-helm-tiller-namespace.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/17-lens-helm-tiller-sa.yml
  non-oss/pharos_pro/addons/kontena-lens/resources/17-lens-helm-tiller-sa.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/18-helm-lens-tiller-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/18-lens-helm-tiller-binding.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/18-lens-helm-user-role.yml.erb
Labels: enhancement, pro

#1017 Support multi-document YAMLs when applying kube resources
  lib/pharos/autoload.rb
  lib/pharos/kube.rb
  lib/pharos/kube/stack.rb
  lib/pharos/yaml_file.rb
  pharos-cluster.gemspec
  spec/fixtures/stacks/multidoc/resources/multidoc.yml
  spec/pharos/addon_spec.rb
Labels: enhancement

#986 Support for oidc configuration
  lib/pharos/config_schema.rb
  lib/pharos/configuration/authentication.rb
  lib/pharos/configuration/oidc.rb
  lib/pharos/kubeadm/cluster_config.rb
  lib/pharos/phases/setup_master.rb
  spec/pharos/kubeadm/cluster_config_spec.rb
Labels: enhancement

#995 Add ingress config option to kontena-lens addon
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement

#1018 Fix non-oss cluster version validation malformed version string error
  non-oss/pharos_pro/phases/validate_version.rb
  non-oss/spec/pharos_pro/phases/validate_version_spec.rb
Labels: bug

#1020 Add priority classes to addons
  addons/cert-manager/resources/20-deployment.yml.erb
  addons/helm/resources/deployment.yml.erb
  addons/host-upgrades/resources/50-daemonset.yml.erb
  addons/ingress-nginx/resources/daemonset.yml.erb
Labels: bug, enhancement

#1023 Revert "Add priority classes to addons (#1020)"
  addons/cert-manager/resources/20-deployment.yml.erb
  addons/helm/resources/deployment.yml.erb
  addons/host-upgrades/resources/50-daemonset.yml.erb
  addons/ingress-nginx/resources/daemonset.yml.erb
Labels: bug

#1008 Log phase completed message
  lib/pharos/phase_manager.rb
Labels: enhancement

#1016 Enable kubelet server tls bootstrap
  lib/pharos/cluster_manager.rb
  lib/pharos/kubeadm/cluster_config.rb
  lib/pharos/kubeadm/kubelet_config.rb
  lib/pharos/phases/configure_kubelet_csr_approver.rb
  lib/pharos/resources/kubelet_rubber_stamp/01-role.yml
  lib/pharos/resources/kubelet_rubber_stamp/02-service-account.yml
  lib/pharos/resources/kubelet_rubber_stamp/03-cluster-role-binding.yml
  lib/pharos/resources/kubelet_rubber_stamp/04-deployment.yml.erb
  lib/pharos/resources/metrics-server/metrics-server-deployment.yml.erb
Labels: enhancement

#1028 Drop phase master: parameter
  lib/pharos/cluster_manager.rb
  lib/pharos/phase.rb
  non-oss/pharos_pro/phases/configure_host.rb
  spec/pharos/phases/configure_calico_spec.rb
  spec/pharos/phases/configure_dns_spec.rb
  spec/pharos/phases/label_node_spec.rb
Labels: chore

#1025 Add pharos-cluster-critical priority class
  addons/helm/resources/deployment.yml.erb
  addons/host-upgrades/resources/50-daemonset.yml.erb
  addons/ingress-nginx/resources/daemonset.yml.erb
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/configure_priority_classes.rb
  lib/pharos/resources/priority_classes/pharos-cluster-critical.yml
Labels: enhancement
