Repository kontena/pharos-cluster, pull requests merged in 2019-12, with the labels that each got.

#1512 Kubernetes v1.15.6
  lib/pharos_cluster.rb
Labels: bug, enhancement

#1517 Packet example: update to use Terraform 0.12
  examples/terraform-packet/README.md
  examples/terraform-packet/cluster.yml
  examples/terraform-packet/main.tf
  examples/terraform-packet/packet-cloud-config-secret.yaml.tpl
  examples/terraform-packet/pharos-addons/packet-ccm/addon.rb
  examples/terraform-packet/pharos-addons/packet-ccm/resources/00-secret.yml.erb
  examples/terraform-packet/pharos-addons/packet-ccm/resources/01-serviceaccount.yml
  examples/terraform-packet/pharos-addons/packet-ccm/resources/02-clusterrole.yml
  examples/terraform-packet/pharos-addons/packet-ccm/resources/03-clusterrolebinding.yml
  examples/terraform-packet/pharos-addons/packet-ccm/resources/04-deployment.yml
  examples/terraform-packet/terraform.example.tfvars
  examples/terraform-packet/versions.tf
Labels: chore, documentation

#1518 Don't attempt to create packet_bgp_session unless bgp_address_pool is defined
  examples/terraform-packet/main.tf
Labels: bug, documentation
