Repository kontena/pharos-cluster, pull requests merged in 2019-05, with the labels that each got.

#1279 Allow to set extra args for kubelet
  lib/pharos/config_schema.rb
  lib/pharos/configuration/host.rb
  lib/pharos/configuration/kubelet.rb
Labels: enhancement

#1301 Fix systemd-resolved DNS issues with host port pods
  lib/pharos/phases/configure_kubelet.rb
Labels: bug

#1305 CRI-O v1.13.6
  lib/pharos_cluster.rb
Labels: bug

#1306 Reload firewalld always when config change is detected
  lib/pharos/phases/configure_firewalld.rb
Labels: bug

#1308 Update Kontena Lens to 1.5.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: bug

#1309 Weave flying-shuttle v0.3.0
  lib/pharos/phases/configure_weave.rb
  lib/pharos/resources/weave/01-cluster-role.yml.erb
  lib/pharos/resources/weave/daemon-set.yml.erb
Labels: enhancement

#1235 Pharos worker up command
  .drone1.yml
  e2e/digitalocean/main.tf
  e2e/drone.sh
  e2e/drone_setup.sh
  e2e/util.sh
  lib/pharos/host/configurer.rb
  lib/pharos/host/ubuntu/scripts/ensure-kubelet.sh
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/root_command.rb
  lib/pharos/scripts/wait-kubelet-proxy.sh
  lib/pharos/worker_up_command.rb
Labels: enhancement

#1313 Ingress-NGINX addon: add resource requests
  addons/ingress-nginx/resources/daemonset.yml.erb
Labels: bug

#1314 Kubernetes v1.13.6
  lib/pharos_cluster.rb
Labels: bug

#1300 Kubernetes v1.14.1
  e2e/travis.sh
  lib/pharos/kubeadm/cluster_config.rb
  lib/pharos/phases/configure_etcd.rb
  lib/pharos/phases/migrate_master.rb
  lib/pharos/scripts/configure-etcd-certs.sh
  lib/pharos/scripts/wait-etcd.sh
  lib/pharos_cluster.rb
  non-oss/pharos_pro/phases/migrate_master.rb
Labels: enhancement

#1211 Share existing SSH connections for port forwarding and detect multi-hop bastion
  lib/pharos/config.rb
  lib/pharos/configuration/bastion.rb
  lib/pharos/phases/connect_ssh.rb
  lib/pharos/transport/ssh.rb
  spec/pharos/config_spec.rb
Labels: enhancement

#1320 Kontena-universal-lb addon
  non-oss/pharos_pro/addons/kontena-universal-lb/addon.rb
  non-oss/pharos_pro/addons/kontena-universal-lb/resources/01_rbac.yml
  non-oss/pharos_pro/addons/kontena-universal-lb/resources/02_operator.yml.erb
Labels: enhancement, pro

#1233 Always tunnel Kube API client through master ssh
  lib/pharos/addon.rb
  lib/pharos/addon_manager.rb
  lib/pharos/command_options/load_config.rb
  lib/pharos/config.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_client.rb
  lib/pharos/transport/local.rb
  non-oss/spec/pharos_pro/addons/backup_spec.rb
  non-oss/spec/pharos_pro/addons/kontena_storage_spec.rb
  non-oss/spec/pharos_pro/addons/network_lb_spec.rb
  spec/pharos/addon_spec.rb
  spec/pharos/addons/cert_manager_spec.rb
  spec/pharos/addons/helm_spec.rb
  spec/pharos/addons/host_upgrades_spec.rb
  spec/pharos/addons/ingress_nginx_spec.rb
  spec/pharos/addons/openebs_spec.rb
  spec/pharos/config_spec.rb
  spec/pharos/phases/configure_client_spec.rb
Labels: enhancement

#1326 Fix Lens redis toleration
  non-oss/pharos_pro/addons/kontena-lens/resources/10-redis-deployment.yml.erb
Labels: bug

#1212 Ingress-NGINX version 0.23.0
  addons/ingress-nginx/addon.rb
  addons/ingress-nginx/resources/daemonset.yml.erb
Labels: enhancement

#1317 cert-manager extra_args
  addons/cert-manager/addon.rb
  addons/cert-manager/resources/20-deployment.yml.erb
Labels: enhancement

#1329 CRI-O v1.14.1
  lib/pharos_cluster.rb
Labels: bug

#1327 Allow user to configure CFS quota setting for kubelet
  lib/pharos/config_schema.rb
  lib/pharos/configuration/kubelet.rb
  lib/pharos/kubeadm/kubelet_config.rb
  lib/pharos/phases/configure_kubelet.rb
  spec/pharos/kubeadm/kubelet_config_spec.rb
Labels: enhancement

#1321 Improved container-runtime upgrade logic
  lib/pharos/host/configurer.rb
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
  lib/pharos/phase.rb
  lib/pharos/phase_manager.rb
  lib/pharos/phases/configure_host.rb
  lib/pharos/phases/validate_version.rb
  lib/pharos/up_command.rb
  non-oss/pharos_pro/phases/configure_host.rb
  non-oss/pharos_pro/phases/validate_version.rb
  non-oss/spec/pharos_pro/phases/validate_version_spec.rb
  spec/pharos/phase_spec.rb
  spec/pharos/phases/validate_version_spec.rb
Labels: enhancement

#1333 Calico 3.6.2
  lib/pharos/phases/configure_calico.rb
Labels: bug

#1334 Weave net 2.5.2
  lib/pharos/phases/configure_weave.rb
Labels: bug

#1338 Revert "Share existing SSH connections for port forwarding and detect multi-hop bastion"
  lib/pharos/config.rb
  lib/pharos/configuration/bastion.rb
  lib/pharos/phases/connect_ssh.rb
  lib/pharos/transport/ssh.rb
  spec/pharos/config_spec.rb
Labels: bug

#1332 Kubernetes v1.14.2
  lib/pharos_cluster.rb
Labels: bug, enhancement

#1339 Add --trust-hosts option to up command
  lib/pharos/terraform/apply_command.rb
  lib/pharos/up_command.rb
Labels: enhancement

#1340 Reorder e2e steps for faster pipeline
  .drone1.yml
Labels: chore

#1228 Make LabelNode phase run on single host
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/label_node.rb
  spec/pharos/phases/label_node_spec.rb
Labels: chore

#1294 Ignore preflight errors during node join
  lib/pharos/phases/join_node.rb
Labels: bug, enhancement

#1331 Disable docker0 bridge
  lib/pharos/host/debian/scripts/configure-docker.sh
  lib/pharos/host/el7/scripts/configure-docker.sh
  lib/pharos/host/ubuntu/scripts/configure-docker.sh
Labels: bug

#1328 Cert manager 0.7.2
  addons/cert-manager/addon.rb
  addons/cert-manager/resources/00-cdrs.yml
  addons/cert-manager/resources/01-cluster-role.yml
  addons/cert-manager/resources/01-service-accounts.yml
  addons/cert-manager/resources/02-service-account.yml
  addons/cert-manager/resources/03-cluster-role-binding.yml
  addons/cert-manager/resources/03-roles.yml
  addons/cert-manager/resources/10-certificate-crd.yml
  addons/cert-manager/resources/10-webhook-service.yml
  addons/cert-manager/resources/11-cluster-issuer-crd.yml
  addons/cert-manager/resources/11-webhook-deployment.yml.erb
  addons/cert-manager/resources/12-issuer-crd.yml
  addons/cert-manager/resources/12-webhook-api-reg.yml
  addons/cert-manager/resources/13-webhook-pki.yml
  addons/cert-manager/resources/14-webhook-config.yml
  addons/cert-manager/resources/20-cainjector-deployment.yml.erb
  addons/cert-manager/resources/30-cert-manager-deployment.yml.erb
  addons/cert-manager/resources/40-issuer.yml.erb
Labels: enhancement

#988 kontena-stats addon
  lib/pharos/resources/weave/10-service.yml
  non-oss/pharos_pro/addons/kontena-lens/resources/07-dashboard-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-stats/addon.rb
  non-oss/pharos_pro/addons/kontena-stats/resources/01-namespace.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/02-configmap.yml.erb
  non-oss/pharos_pro/addons/kontena-stats/resources/03-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-stats/resources/03-prometheus-pvc.yml.erb
  non-oss/pharos_pro/addons/kontena-stats/resources/04-rules.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/05-clusterrole.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/05-service-account.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/06-clusterrole-binding.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/06-service.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/10-node-exporter-ds.yml.erb
  non-oss/pharos_pro/addons/kontena-stats/resources/11-node-exporter-svc.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/50-etcd-scraper-proxy-ds.yml.erb
Labels: enhancement, pro

#1344 Addon deps
  lib/pharos/addon.rb
  lib/pharos/addon_manager.rb
Labels: enhancement

#1348 Add access to Lens service account to create tokenreviews
  non-oss/pharos_pro/addons/kontena-lens/resources/lens-operator-cluster-access-role.yml
Labels: enhancement

#1351 Add kube-state-metrics agent
  non-oss/pharos_pro/addons/kontena-stats/addon.rb
  non-oss/pharos_pro/addons/kontena-stats/resources/12-kube-state-metrics-clusterrole.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/12.kube-state-metrics-sa.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/13-kube-state-metrics-clusterrole-binding.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/14-kube-state-metrics-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-stats/resources/14-kube-state-metrics-svc.yml
Labels: enhancement

#1341 Add Lens license manager
  non-oss/pharos_pro/addons/kontena-lens/resources/19-license-enforcer-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/19-license-enforcer-rbac.yml
  non-oss/pharos_pro/addons/kontena-lens/resources/lens-config-manager-role.yml
Labels: enhancement, pro

#1353 Update Kontena Lens to 1.6.0-alpha.2
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement, pro

#1349 Kontena Storage v0.9.3
  e2e/travis.sh
  lib/pharos/host/configurer.rb
  non-oss/pharos_pro/addons/kontena-storage/addon.rb
  non-oss/pharos_pro/addons/kontena-storage/resources/01-cluster-crd.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/01-filesystem-crd.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/01-objectstore-crd.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/01-pool-crd.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/01-volume-crd.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/02-clusterrole.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/02-global-clusterrole.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/02-role.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/04-clusterrolebinding.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/04-global-clusterrolebinding.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/11-service-accounts.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/11-serviceaccount.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/12-role.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/12-roles.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/13-mgmt-role-binding.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/13-rolebindings.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/14-rolebinding.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/20-pool.yml.erb
  non-oss/pharos_pro/addons/kontena-storage/resources/30-toolbox.yml.erb
  non-oss/pharos_pro/addons/kontena-storage/resources/40-filesystem.yml.erb
  non-oss/pharos_pro/phases/migrate_master.rb
  non-oss/spec/pharos_pro/addons/kontena_storage_spec.rb
Labels: enhancement, pro

#1358 Remove deprecated openebs addon
  addons/openebs/addon.rb
  addons/openebs/resources/00-namespace.yml
  addons/openebs/resources/01-cluster-role.yml
  addons/openebs/resources/02-cluster-role-binding.yml
  addons/openebs/resources/03-psp-role-binding.yml
  addons/openebs/resources/03-service-account.yml
  addons/openebs/resources/10-api-server-deployment.yml.erb
  addons/openebs/resources/11-api-server-service.yml
  addons/openebs/resources/12-provisioner-deployment.yml.erb
  addons/openebs/resources/20-crd-storage-pool-claim.yml
  addons/openebs/resources/21-crd-storage-pool.yml
  addons/openebs/resources/22-storage-class.yml.erb
  addons/openebs/resources/23-crd-volume-policy.yml
  addons/openebs/resources/30-default-storage-pool.yml.erb
  spec/pharos/addons/openebs_spec.rb
Labels: chore

#1359 Fix kontena-storage mgr upgrade wait
  non-oss/pharos_pro/addons/kontena-storage/addon.rb
Labels: bug, pro
