Repository kontena/pharos-cluster, pull requests merged in 2019-06, with the labels that each got.

#1364 More SSH keepalive in e2e
  e2e/drone.sh
  lib/pharos/transport.rb
Labels: bug, chore

#1368 Run "docker ps" in subshell using sudo
  lib/pharos/host/configurer.rb
Labels: bug

#1347 Only set cloud provider in worker up when given
  lib/pharos/worker_up_command.rb
Labels: bug

#1365 Fix debian firewalld start error
  lib/pharos/host/debian/scripts/configure-essentials.sh
  lib/pharos/host/debian/scripts/configure-firewalld.sh
Labels: bug

#1370 Cert-manager: allow to set multiple issuers/clusterissuers
  addons/cert-manager/addon.rb
  addons/cert-manager/resources/11-webhook-deployment.yml.erb
  addons/cert-manager/resources/12-webhook-pki.yml
  addons/cert-manager/resources/13-webhook-api-reg.yml
  addons/cert-manager/resources/40-issuer.yml.erb
  spec/pharos/addons/cert_manager_spec.rb
Labels: enhancement

#1372 Retry initial SSH connection opening for 60 seconds
  lib/pharos/phases/connect_ssh.rb
Labels: enhancement

#1371 Terraform 0.12 support
  .drone1.yml
  e2e/digitalocean/terraform-0.12/cluster.yml
  e2e/digitalocean/terraform-0.12/main.tf
  e2e/digitalocean/terraform-0.12/terraform.tfvars
  e2e/drone_setup.sh
  lib/pharos/autoload.rb
  lib/pharos/command_options/tf_json.rb
  lib/pharos/terraform/json_parser.rb
  lib/pharos/terraform/legacy_json_parser.rb
  spec/pharos/terraform/json_parser_spec.rb
  spec/pharos/terraform/legacy_json_parser_spec.rb
Labels: bug, enhancement

#1373 k8s-client v0.10.1
  pharos-cluster.gemspec
Labels: bug, chore

#1374 Don't log pharos kubelet proxy wait retries
  lib/pharos/phases/configure_kubelet.rb
Labels: bug, chore

#1376 Metrics-server 0.3.2
  lib/pharos/phases/configure_metrics.rb
Labels: bug, enhancement

#1355 Add node_selector and tolerations config options to Kontena Lens
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/07-dashboard-deployment.yml.erb
Labels: enhancement, pro

#1375 Helm addon: version 2.13.1
  addons/helm/addon.rb
Labels: enhancement

#1378 Bump Lens Helm tiller to 2.13.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/18-helm-lens-tiller-deployment.yml.erb
Labels: enhancement, pro

#1377 Bump Kontena Lens to 1.6.0-beta.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement, pro

#1360 Fix weave net ipam consensus race cond
  lib/pharos/phases/configure_weave.rb
  lib/pharos/resources/weave/01-cluster-role.yml.erb
  spec/pharos/phases/configure_weave_spec.rb
Labels: bug

#1381 Weave flying shuttle 0.3.1
  lib/pharos/phases/configure_weave.rb
Labels: bug, enhancement

#1380 Fix lens dashboard tolerations
  non-oss/pharos_pro/addons/kontena-lens/resources/07-dashboard-deployment.yml.erb
Labels: bug, pro

#1382 Use separate version numbers for Lens components
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/04-user-management-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/06-authenticator-daemonset.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/07-dashboard-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/10-redis-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/15-helm-api-statefulset.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/16-k8s-resource-applier-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-lens/resources/19-license-enforcer-deployment.yml.erb
Labels: enhancement, pro

#1388 Fix kontena-storage discovery toleration
  non-oss/pharos_pro/addons/kontena-storage/resources/05-deployment.yml.erb
Labels: bug, pro

#1385 Fix previous config retrieval
  lib/pharos/phase.rb
  lib/pharos/phases/load_cluster_configuration.rb
Labels: bug

#1386 Lower SSH connect timeout from 60 to 5 seconds [cluster-e2e]
  lib/pharos/phases/connect_ssh.rb
  lib/pharos/transport.rb
Labels: bug, enhancement

#1387 Fix kontena-storage toolbox deployment
  non-oss/pharos_pro/addons/kontena-storage/addon.rb
  non-oss/pharos_pro/addons/kontena-storage/resources/30-toolbox.yml.erb
Labels: bug, pro

#1391 Kubernetes v1.14.3
  lib/pharos_cluster.rb
Labels: bug

#1392 CRI-O v1.14.2
  lib/pharos_cluster.rb
Labels: bug

#1396 Kontena-universal-lb addon: v0.1.1
  non-oss/pharos_pro/addons/kontena-universal-lb/addon.rb
Labels: bug, pro

#1399 Fix interactive SSH connection opening
  lib/pharos/exec_command.rb
Labels: bug

#1394 Kontena Lens 1.6.0-rc.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/07-dashboard-deployment.yml.erb
Labels: enhancement, pro

#1393 Add kube-rbac-proxy to kontena-stats
  non-oss/pharos_pro/addons/kontena-stats/addon.rb
  non-oss/pharos_pro/addons/kontena-stats/resources/02-configmap.yml.erb
  non-oss/pharos_pro/addons/kontena-stats/resources/15-rbac-proxy-sa.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/16-rbac-proxy-cluster-role-binding.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/16-rbac-proxy-cluster-role.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/17-rbac-proxy-cm.yaml
  non-oss/pharos_pro/addons/kontena-stats/resources/17-rbac-proxy-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-stats/resources/17-rbac-proxy-service.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/18-prometheus-network-policy.yml
Labels: enhancement, pro

#1404 Kontena Lens: license enforcer 0.2.0
  lib/pharos/version.rb
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/resources/19-license-enforcer-rbac.yml
Labels: bug, pro

#1400 Fix line joining in gather facts spec
  spec/pharos/phases/gather_facts_spec.rb
Labels: chore

#1407 Add ceph-prom-exporter to kontena-storage addon
  non-oss/pharos_pro/addons/kontena-storage/resources/50-ceph-prom-exporter-rbac.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/51-ceph-prom-exporter-deployment.yml.erb
Labels: enhancement, pro

#1271 Make package repos configurable
  lib/pharos/autoload.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/host.rb
  lib/pharos/configuration/repository.rb
  lib/pharos/host/configurer.rb
  lib/pharos/host/debian/debian.rb
  lib/pharos/host/debian/debian_stretch.rb
  lib/pharos/host/debian/scripts/repos/pharos_stretch.sh
  lib/pharos/host/debian/scripts/repos/update.sh
  lib/pharos/host/el7/el7.rb
  lib/pharos/host/el7/scripts/repos/pharos_centos7.sh
  lib/pharos/host/el7/scripts/repos/update.sh
  lib/pharos/host/ubuntu/scripts/repos/pharos_bionic.sh
  lib/pharos/host/ubuntu/scripts/repos/pharos_xenial.sh
  lib/pharos/host/ubuntu/scripts/repos/update.sh
  lib/pharos/host/ubuntu/ubuntu.rb
  lib/pharos/host/ubuntu/ubuntu_bionic.rb
  lib/pharos/host/ubuntu/ubuntu_xenial.rb
  spec/fixtures/cluster_with_repos.yml
  spec/pharos/command_options/load_config_spec.rb
  spec/pharos/host/configurer_spec.rb
Labels: enhancement

#1409 Kontena Stats: allow to toggle persistence/node_exporter/state_metrics
  non-oss/pharos_pro/addons/kontena-stats/addon.rb
  non-oss/pharos_pro/addons/kontena-stats/resources/03-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-stats/resources/10-node-exporter-ds.yml.erb
  non-oss/pharos_pro/addons/kontena-stats/resources/14-kube-state-metrics-deployment.yml.erb
Labels: enhancement

#1410 Kontena Storage: ceph-prom-exporter 0.2.0
  non-oss/pharos_pro/addons/kontena-storage/resources/51-ceph-prom-exporter-deployment.yml.erb
Labels: bug, pro

#1411 Kontena Lens 1.6.0-rc.2
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement, pro

#1413 cert-manager: optional webhook
  .drone1.yml
  addons/cert-manager/addon.rb
  addons/cert-manager/resources/11-webhook-deployment.yml.erb
  addons/cert-manager/resources/12-webhook-pki.yml.erb
  addons/cert-manager/resources/13-webhook-api-reg.yml.erb
  addons/cert-manager/resources/14-webhook-config.yml.erb
  e2e/digitalocean/cluster.yml
  e2e/digitalocean/main.tf
  e2e/digitalocean/terraform-0.12/main.tf
  e2e/drone.sh
  e2e/drone_setup.sh
Labels: bug, enhancement

#1416 Fix e2e worker up fw issue
  .drone1.yml
  e2e/digitalocean/cluster.yml
Labels: bug, chore

#1421 Kontena Lens 1.6.0-rc.3
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement, pro

#1422 Allow to set addon defaults values without typed structs
  lib/pharos/addon.rb
  spec/pharos/addon_spec.rb
Labels: enhancement

#1419 Ingress-NGINX: allow optionally deploy as service type=loadbalancer
  addons/ingress-nginx/addon.rb
  addons/ingress-nginx/resources/07-configmap.yml.erb
  addons/ingress-nginx/resources/deployment.yml.erb
Labels: enhancement

#1423 Kontena Stats: switch to StatefulSet
  non-oss/pharos_pro/addons/kontena-stats/addon.rb
  non-oss/pharos_pro/addons/kontena-stats/resources/03-prometheus-pvc.yml.erb
  non-oss/pharos_pro/addons/kontena-stats/resources/03-statefulset.yml.erb
Labels: bug, enhancement

#1425 Add LENS_VERSION env var to lens deployment
  non-oss/pharos_pro/addons/kontena-lens/resources/07-dashboard-deployment.yml.erb
Labels: enhancement, pro

#1430 Kontena Lens 1.6.0
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement, pro

#1432 Add system:auth-delegator binding to cert-manager-webhook service account
  addons/cert-manager/resources/03-roles.yml
Labels: bug

#1433 Kontena Lens addon: v1.6.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: bug, enhancement
