Repository kontena/pharos-cluster, pull requests merged in 2019-03, with the labels that each got.

#1128 Handle non-oss cluster-info migration
  lib/pharos/phases/mixins/cluster_version.rb
  lib/pharos/phases/validate_version.rb
  non-oss/pharos_pro/phases/migrate_master.rb
Labels: chore, pro

#1129 Configure used node shell image
  non-oss/pharos_pro/addons/kontena-lens/resources/07-dashboard-deployment.yml.erb
Labels: enhancement

#1130 Update Kontena Lens to 1.5.0-alpha.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement

#1127 Fix license key validation and add specs
  non-oss/pharos_pro/license_key.rb
  non-oss/spec/pharos_pro/license_key_spec.rb
Labels: bug

#1108 Load addons using AddonContext instance_eval
  e2e/cluster.yml
  e2e/digitalocean/cluster.yml
  lib/pharos/addon.rb
  lib/pharos/addon_context.rb
  lib/pharos/addon_manager.rb
  lib/pharos/autoload.rb
  lib/pharos/core-ext/ip_addr_loopback.rb
  lib/pharos/phases/store_cluster_configuration.rb
  lib/pharos/version_command.rb
  non-oss/pharos_pro/addons/kontena-backup/addon.rb
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
  non-oss/pharos_pro/addons/kontena-storage/addon.rb
  non-oss/pharos_pro/addons/pharos-license-enforcer/addon.rb
  non-oss/spec/pharos_pro/addons/backup_spec.rb
  non-oss/spec/pharos_pro/addons/kontena_storage_spec.rb
  non-oss/spec/pharos_pro/addons/network_lb_spec.rb
  spec/pharos/addon_manager_spec.rb
  spec/pharos/addon_spec.rb
  spec/pharos/addons/cert_manager_spec.rb
  spec/pharos/addons/host_upgrades_spec.rb
  spec/pharos/addons/ingress_nginx_spec.rb
  spec/pharos/addons/openebs_spec.rb
Labels: bug, enhancement

#1139 Add --tf-json to pharos reset command
  lib/pharos/reset_command.rb
Labels: bug

#1137 Fix Host#local? raising IPAddr::InvalidAddressError
  lib/pharos/configuration/host.rb
  spec/pharos/configuration/host_spec.rb
Labels: bug

#1140 Update kubeadm config schemas to v1beta1
  lib/pharos/kubeadm/cluster_config.rb
  lib/pharos/kubeadm/init_config.rb
  spec/pharos/kubeadm/cluster_config_spec.rb
  spec/pharos/kubeadm/init_config_spec.rb
Labels: enhancement

#1144 Use cdn for downloading bintray public key
  lib/pharos/host/debian/scripts/repos/pharos_stretch.sh
  lib/pharos/host/el7/scripts/repos/pharos_centos7.sh
  lib/pharos/host/ubuntu/scripts/repos/pharos_bionic.sh
  lib/pharos/host/ubuntu/scripts/repos/pharos_xenial.sh
Labels: bug, chore

#1133 Drop IPAddr Loopback backport usage
  lib/pharos/phases/gather_facts.rb
Labels: chore

#1134 Set or generate names for clusters
  e2e/digitalocean/main.tf
  e2e/digitalocean/terraform.tfvars
  lib/pharos/cluster_manager.rb
  lib/pharos/command_options/tf_json.rb
  lib/pharos/config.rb
  lib/pharos/config_schema.rb
  lib/pharos/kube/config.rb
  lib/pharos/kubeadm/cluster_config.rb
  lib/pharos/kubeadm/config_generator.rb
  lib/pharos/phases/configure_cluster_name.rb
  lib/pharos/phases/store_cluster_configuration.rb
  lib/pharos/terraform/json_parser.rb
  lib/pharos/up_command.rb
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement

#1147 Read cluster name from pharos-config on license assign
  non-oss/pharos_pro/autoload.rb
  non-oss/pharos_pro/commands/license_assign_command.rb
  non-oss/pharos_pro/commands/license_inspect_command.rb
  non-oss/pharos_pro/license_key_command_option.rb
  non-oss/spec/pharos_pro/commands/license_assign_command_spec.rb
Labels: bug

#1146 Decorate output based on message severity
  lib/pharos/core-ext/colorize.rb
  lib/pharos/phase.rb
Labels: enhancement

#1154 Change localApiEndpoint to localAPIEndpoint on InitConfiguration
  lib/pharos/kubeadm/init_config.rb
  spec/pharos/kubeadm/init_config_spec.rb
Labels: bug

#1151 Update Kontena Lens to 1.5.0-alpha.3
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement

#1153 Increase Helm API memory limit
  non-oss/pharos_pro/addons/kontena-lens/resources/15-helm-api-statefulset.yml.erb
Labels: bug

#1150 Fix generated node selectors for nginx-ingress
  addons/ingress-nginx/resources/daemonset.yml.erb
Labels: bug

#1145 Add "terraform" alias for "tf" subcommand
  lib/pharos/root_command.rb
Labels: enhancement

#1155 Allow to enable feature gates
  lib/pharos/cluster_manager.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/control_plane.rb
  lib/pharos/configuration/kubelet.rb
  lib/pharos/kubeadm/cluster_config.rb
  lib/pharos/kubeadm/kubelet_config.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/reconfigure_kubelet.rb
  lib/pharos/scripts/kubeadm-reconfigure.sh
  spec/pharos/kubeadm/cluster_config_spec.rb
  spec/pharos/kubeadm/kubelet_config_spec.rb
  spec/pharos/phases/reconfigure_kubelet_spec.rb
Labels: enhancement

#1159 Bump enforcer to 0.2.0
  non-oss/pharos_pro/addons/pharos-license-enforcer/addon.rb
Labels: enhancement, pro

#1160 Update Kontena Lens to 1.5.0-rc.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement

#1157 Reimplement license inspect command and refactor assign + config loading
  lib/pharos/command_options/load_config.rb
  lib/pharos/phases/configure_cluster_name.rb
  lib/pharos/phases/load_cluster_configuration.rb
  lib/pharos/reset_command.rb
  lib/pharos/up_command.rb
  non-oss/pharos_pro/commands/license_assign_command.rb
  non-oss/pharos_pro/commands/license_inspect_command.rb
  non-oss/pharos_pro/license_key.rb
  non-oss/spec/pharos_pro/commands/license_assign_command_spec.rb
  spec/fixtures/cluster.master_and_worker.yml
  spec/pharos/command_options/load_config_spec.rb
Labels: chore, enhancement

#1161 Fix pharos-license-enforcer default interval
  non-oss/pharos_pro/addons/pharos-license-enforcer/resources/01-license-enforcer-daemonset.yml.erb
Labels: bug

#1162 Allow to install helm charts via helm addon
  addons/helm/addon.rb
  addons/helm/resources/deployment.yml.erb
  spec/pharos/addons/helm_spec.rb
Labels: enhancement

#1158 Upgrade net-ssh to 5.2.0
  pharos-cluster.gemspec
Labels: bug, chore, enhancement

#1169 Add missing terraform.examples.tfvars to packet example
  examples/terraform-packet/README.md
  examples/terraform-packet/terraform.example.tfvars
Labels: chore, documentation

#1177 Improve oss upgrade warning
  lib/pharos/up_command.rb
Labels: chore, documentation

#1172 Calico 3.6
  lib/pharos/config_schema.rb
  lib/pharos/configuration/network.rb
  lib/pharos/phases/configure_calico.rb
  lib/pharos/resources/calico/01-all-crds.yml
  lib/pharos/resources/calico/10-cluster-role.yml
  lib/pharos/resources/calico/10-rbac-node.yml
  lib/pharos/resources/calico/11-serviceaccount.yml
  lib/pharos/resources/calico/12-cluster-role-binding.yml
  lib/pharos/resources/calico/15-rbac-controllers.yml
  lib/pharos/resources/calico/20-configmap.yml.erb
  lib/pharos/resources/calico/21-metrics-service.yml.erb
  lib/pharos/resources/calico/25-node-daemonset.yml.erb
  lib/pharos/resources/calico/30-controller-deployment.yml.erb
  lib/pharos/resources/calico/crd-bgpconfigurations.yml
  lib/pharos/resources/calico/crd-bgppeers.yml
  lib/pharos/resources/calico/crd-clusterinformations.yml
  lib/pharos/resources/calico/crd-felixconfigurations.yml
  lib/pharos/resources/calico/crd-globalnetworkpolicies.yml
  lib/pharos/resources/calico/crd-globalnetworksets.yml
  lib/pharos/resources/calico/crd-hostendpoints.yml
  lib/pharos/resources/calico/crd-ippools.yml
  lib/pharos/resources/calico/crd-networkpolicies.yml
Labels: enhancement

#1181 Allow to use custom node roles for workers
  lib/pharos/configuration/host.rb
  spec/pharos/configuration/host_spec.rb
Labels: enhancement

#1175 Reduce retry logging verbosity
  lib/pharos/logging.rb
  lib/pharos/phase.rb
  lib/pharos/phase_manager.rb
  lib/pharos/retry.rb
Labels: enhancement

#1183 Update Kontena Lens to 1.5.0-rc.2
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement

#1185 Drop Net::SSH::Gateway dependency
  e2e/digitalocean/main.tf
  lib/pharos/config.rb
  lib/pharos/configuration/bastion.rb
  lib/pharos/transport/command/ssh.rb
  lib/pharos/transport/local.rb
  lib/pharos/transport/ssh.rb
  pharos-cluster.gemspec
  spec/pharos/config_spec.rb
Labels: enhancement

#1156 Pharos dev console
  lib/pharos/command.rb
Labels: chore

#1192 Add missing flags for tf destroy
  lib/pharos/terraform/apply_command.rb
  lib/pharos/terraform/base_command.rb
  lib/pharos/terraform/destroy_command.rb
Labels: bug

#1195 e2e: tag droplets for easier gc
  e2e/digitalocean/cluster.yml
  e2e/digitalocean/main.tf
  e2e/digitalocean/terraform.tfvars
Labels: chore

#1193 Cri-o v1.13.3
  e2e/drone.sh
  lib/pharos_cluster.rb
Labels: enhancement

#1165 Add Addon#to_s to improve spec error messages
  lib/pharos/addon.rb
Labels: chore

#1142 Fix global option parsing and phase thread error handling
  lib/pharos/command.rb
  lib/pharos/kube.rb
  lib/pharos/logging.rb
  lib/pharos/phase.rb
  lib/pharos/phase_manager.rb
  lib/pharos/phases/gather_facts.rb
  lib/pharos/transport/command/result.rb
  non-oss/pharos_pro/phases/configure_host.rb
Labels: bug

#1200 Enforcer as static pods
  non-oss/pharos_pro/addons/pharos-license-enforcer/addon.rb
  non-oss/pharos_pro/addons/pharos-license-enforcer/resources/01-license-enforcer-daemonset.yml.erb
  non-oss/pharos_pro/addons/pharos-license-enforcer/resources/02-rbac.yml
Labels: enhancement

#1197 helm addon: fix chart name env
  addons/helm/addon.rb
Labels: bug

#1196 Download el7 cfssl from pharos repo
  lib/pharos/host/el7/scripts/configure-cfssl.sh
Labels: bug, enhancement

#1202 Fix misleading error message when ping command missing
  lib/pharos/phases/validate_host.rb
Labels: bug

#1189 Allow to disable node local DNS cache
  lib/pharos/config_schema.rb
  lib/pharos/configuration/network.rb
  lib/pharos/kubeadm/kubelet_config.rb
  lib/pharos/phases/configure_dns.rb
Labels: enhancement

#1191 Add host ssh_port option
  lib/pharos/config_schema.rb
  lib/pharos/configuration/bastion.rb
  lib/pharos/configuration/host.rb
  lib/pharos/terraform/json_parser.rb
  lib/pharos/transport.rb
  spec/pharos/config_spec.rb
Labels: enhancement

#1199 Pro: pharos license assign for another cluster
  non-oss/pharos_pro/commands/license_assign_command.rb
  non-oss/pharos_pro/commands/license_inspect_command.rb
  non-oss/spec/pharos_pro/commands/license_assign_command_spec.rb
Labels: enhancement, pro

#1203 Increase exec error verbosity
  lib/pharos/error.rb
  lib/pharos/logging.rb
  lib/pharos/phase.rb
Labels: enhancement

#1205 Kontena Lens to 1.5.0
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement

#1213 Fix ED25519 passphrase prompting
  lib/pharos/transport/ssh.rb
Labels: bug

#1214 Fix enforcer check interval
  non-oss/pharos_pro/addons/pharos-license-enforcer/addon.rb
Labels: bug, pro

#1216 Fix autoload loading everything always
  lib/pharos/autoload.rb
  lib/pharos/configuration/host.rb
  lib/pharos/kube.rb
Labels: bug

#1218 Open SSH connections parallelly
  lib/pharos/cluster_manager.rb
  lib/pharos/transport/ssh.rb
Labels: enhancement

#1217 Move Configuration::Struct to configuration/struct.rb
  lib/pharos/autoload.rb
  lib/pharos/configuration/struct.rb
Labels: chore

#1208 Fix SSH event loop deadlock
  lib/pharos/transport/ssh.rb
Labels: bug

#1220 Fix version validation when cluster SSL has expired or is invalid
  lib/pharos/phases/load_cluster_configuration.rb
  lib/pharos/phases/validate_version.rb
Labels: bug

#1223 Fix excess CPU usage while waiting for phases to finish
  lib/pharos/phase_manager.rb
Labels: bug

#1226 Switch to drone 1.0
  .drone.yml
  .drone1.yml
Labels: chore

#1222 Fix firewalld reload issues
  lib/pharos/phases/configure_calico.rb
  lib/pharos/phases/configure_custom_network.rb
  lib/pharos/phases/configure_firewalld.rb
  lib/pharos/phases/configure_weave.rb
  lib/pharos/resources/calico/25-node-daemonset.yml.erb
  lib/pharos/resources/weave/daemon-set.yml.erb
  lib/pharos/scripts/configure-firewalld.sh
Labels: bug

#1229 Freeze kubernetes-cni version
  lib/pharos/host/debian/scripts/ensure-kubelet.sh
  lib/pharos/host/debian/scripts/install-kube-packages.sh
  lib/pharos/host/debian/scripts/reset.sh
  lib/pharos/host/el7/scripts/ensure-kubelet.sh
  lib/pharos/host/el7/scripts/install-kube-packages.sh
  lib/pharos/host/ubuntu/scripts/ensure-kubelet.sh
  lib/pharos/host/ubuntu/scripts/install-kube-packages.sh
  lib/pharos/host/ubuntu/scripts/reset.sh
  lib/pharos/phases/configure_etcd.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos_cluster.rb
Labels: bug

#1230 Backport 1229 to 2.2
  lib/pharos/host/debian/scripts/ensure-kubelet.sh
  lib/pharos/host/debian/scripts/install-kube-packages.sh
  lib/pharos/host/debian/scripts/reset.sh
  lib/pharos/host/el7/scripts/ensure-kubelet.sh
  lib/pharos/host/el7/scripts/install-kube-packages.sh
  lib/pharos/host/ubuntu/scripts/ensure-kubelet.sh
  lib/pharos/host/ubuntu/scripts/install-kube-packages.sh
  lib/pharos/host/ubuntu/scripts/reset.sh
  lib/pharos/phases/configure_etcd.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos_cluster.rb
Labels: bug

#1237 Fix firewalld reload
  .drone1.yml
  e2e/digitalocean/terraform.tfvars
  e2e/drone.sh
  e2e/drone_setup.sh
  e2e/util.sh
  lib/pharos/scripts/configure-firewalld.sh
Labels: bug

#1234 Drop unused constant PROXY_ADDRESS from JoinNode
  lib/pharos/phases/join_node.rb
Labels: chore

#1227 Kubernetes 1.13.5
  lib/pharos/host/debian/scripts/install-kube-packages.sh
  lib/pharos/host/ubuntu/scripts/install-kube-packages.sh
  lib/pharos/resources/calico/25-node-daemonset.yml.erb
  lib/pharos_cluster.rb
Labels: bug

#1241 Fix firewalld systemd start & checks
  e2e/digitalocean/cluster.yml
  lib/pharos/host/debian/scripts/configure-firewalld.sh
  lib/pharos/host/el7/scripts/configure-firewalld.sh
  lib/pharos/host/ubuntu/scripts/configure-firewalld.sh
  lib/pharos/scripts/configure-firewalld.sh
Labels: bug
