Repository kontena/pharos-cluster, pull requests merged in 2019-04, with the labels that each got.

#1249 Fix cni dependency error on upgrade
  lib/pharos/host/debian/scripts/install-kube-packages.sh
  lib/pharos/host/ubuntu/scripts/install-kube-packages.sh
  lib/pharos/phases/configure_kubelet.rb
Labels: bug

#1245 E2e test proxied environments (airgap-ish)
  .drone1.yml
  e2e/digitalocean/main.tf
  e2e/drone.sh
  lib/pharos/phases/configure_host.rb
  lib/pharos/phases/configure_master.rb
  lib/pharos/scripts/kubeadm-init.sh
  lib/pharos/scripts/kubeadm-reconfigure.sh
  lib/pharos/scripts/kubeadm-renew-certs.sh
  lib/pharos/terraform/json_parser.rb
  lib/pharos/transport.rb
  spec/fixtures/terraform/tf.json
  spec/pharos/terraform/json_parser_spec.rb
Labels: bug, enhancement

#1257 Remove kubernetes-cni on el7 reset
  lib/pharos/host/el7/scripts/reset.sh
Labels: bug

#1254 Drop non-functional shell variable exports when updating env file
  lib/pharos/host/configurer.rb
  spec/pharos/host/configurer_spec.rb
Labels: bug

#1253 Set environment for local command execs
  lib/pharos/transport/command/local.rb
Labels: bug

#1259 Connect to local etcd peer first
  lib/pharos/kubeadm/cluster_config.rb
  spec/pharos/kubeadm/cluster_config_spec.rb
Labels: bug

#1267 [v2.2] Fix kubelet not upgraded automatically (regression from 1230)
  lib/pharos/host/debian/scripts/install-kube-packages.sh
  lib/pharos/host/el7/scripts/install-kube-packages.sh
  lib/pharos/host/ubuntu/scripts/install-kube-packages.sh
Labels: bug

#1266 Fix license assign NoMethodError
  non-oss/pharos_pro/commands/license_assign_command.rb
Labels: bug, pro

#1273 Pin rubocop to 0.66 for now
  pharos-cluster.gemspec
Labels: chore

#1272 Raise node-local-dns mem limit to 100Mi
  lib/pharos/resources/node_local_dns/daemonset.yml.erb
Labels: bug

#1275 Helm addon: wait for helm chart job to complete
  addons/helm/addon.rb
  e2e/cluster.yml
Labels: bug

#1282 Fix coredns version
  lib/pharos/phases/configure_dns.rb
  lib/pharos_cluster.rb
  spec/pharos/phases/configure_dns_spec.rb
Labels: bug

#1269 Fix reset command remaining masters validation
  lib/pharos/reset_command.rb
  spec/pharos/reset_command_spec.rb
Labels: bug

#1285 Add kubernetes-cni package to version list
  lib/pharos/phases/configure_kubelet.rb
Labels: bug

#1287 CRI-O v1.13.4
  lib/pharos_cluster.rb
Labels: bug

#1286 pharos-license-enforcer v0.3.1
  non-oss/pharos_pro/addons/pharos-license-enforcer/addon.rb
Labels: bug, pro

#1261 Fix drone build status badge
  README.md
Labels: chore

#1293 Add ExternalIP to kubelet-preferred-address-types for metric-server
  lib/pharos/resources/metrics-server/metrics-server-deployment.yml.erb
Labels: bug

#1291 Read kubernetes api endpoint from cluster config
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: bug

#1260 Validate configuration host address uniqueness
  lib/pharos/config_schema.rb
  spec/pharos/config_spec.rb
Labels: enhancement

#1280 Fix local transport mode detect
  lib/pharos/configuration/host.rb
Labels: bug

#1296 Switch master branch to 2.4 series
  lib/pharos/version.rb
Labels: chore

#1186 Improved out-of-tree cloud provider support
  lib/pharos/autoload.rb
  lib/pharos/cloud/hcloud.rb
  lib/pharos/cloud/packet.rb
  lib/pharos/cloud/provider.rb
  lib/pharos/cloud/provider_registry.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/config_schema.rb
  lib/pharos/configuration/cloud.rb
  lib/pharos/kube/stack.rb
  lib/pharos/kubeadm/cluster_config.rb
  lib/pharos/kubeadm/kubelet_config.rb
  lib/pharos/phase.rb
  lib/pharos/phases/configure_cloud_provider.rb
  lib/pharos/phases/configure_kubelet.rb
  lib/pharos/phases/setup_master.rb
  lib/pharos/resources/csi-crds/csidriver.yml
  lib/pharos/resources/csi-crds/csinodeinfo.yml
  lib/pharos/resources/hcloud/hcloud-ccm.yml
  lib/pharos/resources/hcloud/hcloud-csi.yml.erb
  lib/pharos/resources/packet/01-serviceaccount.yml
  lib/pharos/resources/packet/02-clusterrole.yml
  lib/pharos/resources/packet/03-clusterrolebinding.yml
  lib/pharos/resources/packet/04-deployment.yml
  spec/pharos/kubeadm/cluster_config_spec.rb
Labels: enhancement

#1297 Firewalld: remove masquerade
  lib/pharos/scripts/configure-firewalld.sh
Labels: bug

#1298 Kontena Lens: add missing redis network policy
  non-oss/pharos_pro/addons/kontena-lens/resources/02-redis-network-policy.yml
Labels: bug, pro

#953 pharos-cloud-controller
  lib/pharos/cloud/pharos.rb
  lib/pharos/configuration/host.rb
  lib/pharos/phases/configure_cloud_provider.rb
  lib/pharos/resources/pharos/00-service-account.yml
  lib/pharos/resources/pharos/01-cluster-role-controller-manager.yml
  lib/pharos/resources/pharos/02-cluster-role-node-controller.yml
  lib/pharos/resources/pharos/03-cluster-role-pvl-controller.yml
  lib/pharos/resources/pharos/10-cluster-role-binding-node-controller.yml
  lib/pharos/resources/pharos/11-cluster-role-binding-pvl-controller.yml
  lib/pharos/resources/pharos/12-cluster-role-binding-ccm.yml
  lib/pharos/resources/pharos/13-cluster-role-pharos-cloud-controller.yml
  lib/pharos/resources/pharos/14-cluster-role-binding-pharos-cloud-controller.yml
  lib/pharos/resources/pharos/20-deployment.yml.erb
  spec/pharos/configuration/host_spec.rb
  spec/pharos/phases/label_node_spec.rb
Labels: enhancement

#1221 Drop the "optional:" keyword from ConfigureClient phase
  lib/pharos/cluster_manager.rb
  lib/pharos/phases/configure_client.rb
  lib/pharos/phases/load_cluster_configuration.rb
Labels: chore

#1303 Reload firewalld when removing masquerade
  lib/pharos/phases/configure_firewalld.rb
Labels: bug
