Repository kontena/pharos-cluster, pull requests merged in 2019-02, with the labels that each got.

#1034 Add bin/pharos to later replace bin/pharos-cluster
  bin/pharos
  bin/pharos-cluster
  build/drone/ubuntu.sh
  build/drone/ubuntu_oss.sh
  build/travis/macos.sh
  build/travis/macos_oss.sh
Labels: chore

#1036 Pin kubelet tls ciphers
  kube-bench/results.md
  lib/pharos/kubeadm/kubelet_config.rb
Labels: enhancement

#1041 Firewalld: masquerade default zone
  lib/pharos/scripts/configure-firewalld.sh
Labels: bug

#1042 Upload oss binary to github
  build/drone/ubuntu_oss.sh
  build/travis/macos_oss.sh
Labels: chore

#1043 Recreate etcd pod only if version changes
  lib/pharos/scripts/configure-etcd.sh
Labels: bug

#1051 Retry connection-reset-by-peer errors
  lib/pharos/phase_manager.rb
Labels: bug

#1047 Update Kontena Lens to 1.4.0
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement

#1059 Don't reinitialize phase manager for every phase
  lib/pharos/cluster_manager.rb
Labels: bug

#1061 Add network LB to vagrant/centos example
  examples/vagrant/centos7/README.md
  examples/vagrant/centos7/cluster.yml
Labels: chore, documentation

#1060 KubeletConfig readOnlyPort should be an integer
  lib/pharos/kubeadm/kubelet_config.rb
  spec/pharos/kubeadm/kubelet_config_spec.rb
Labels: bug

#1064 Use docker 18.06.2 on Debian
  lib/pharos/host/debian/debian_stretch.rb
  lib/pharos/host/debian/scripts/configure-docker.sh
Labels: bug

#1065 Fix typo in debian docker version
  lib/pharos/host/debian/debian_stretch.rb
Labels: bug, chore

#884 Retry cluster version validation without ssl verify if it fails
  lib/pharos/phases/validate_version.rb
Labels: enhancement

#936 Change the defaults of configuration arrays and hashes to procs
  addons/openebs/addon.rb
  lib/pharos/config.rb
  lib/pharos/configuration/container_runtime.rb
Labels: bug

#1066 Update Kontena Lens to 1.4.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: bug

#1063 Update gemspec to avoid warnings
  pharos-cluster.gemspec
Labels: chore

#1067 Allow to install latest release/revision for given cri-o version
  lib/pharos/host/debian/scripts/configure-cri-o.sh
  lib/pharos/host/ubuntu/scripts/configure-cri-o.sh
Labels: bug

#1070 Raise ingress-nginx default backend limits
  addons/ingress-nginx/resources/default-backend.yml.erb
Labels: bug

#1077 Fix firewalld config schema
  lib/pharos/config_schema.rb
Labels: bug

#1079 Generic env handling for calico, including enabling metrics
  lib/pharos/config_schema.rb
  lib/pharos/configuration/network.rb
  lib/pharos/phases/configure_calico.rb
  lib/pharos/resources/calico/daemonset.yml.erb
  lib/pharos/resources/calico/metrics-service.yml.erb
Labels: enhancement

#1087 pharos tf apply/destroy
  e2e/drone.sh
  examples/terraform-aws/README.md
  examples/terraform-do/README.md
  examples/terraform-packet/README.md
  lib/pharos/autoload.rb
  lib/pharos/command_options/load_config.rb
  lib/pharos/command_options/tf_json.rb
  lib/pharos/exec_command.rb
  lib/pharos/kubeconfig_command.rb
  lib/pharos/phase_manager.rb
  lib/pharos/root_command.rb
  lib/pharos/terraform/apply_command.rb
  lib/pharos/terraform/base_command.rb
  lib/pharos/terraform/destroy_command.rb
  lib/pharos/terraform_command.rb
  lib/pharos/up_command.rb
  spec/pharos/command_options/load_config_spec.rb
  spec/pharos/command_options/tf_json_spec.rb
Labels: enhancement

#1085 Calico 3.5.1
  lib/pharos/phases/configure_calico.rb
  lib/pharos/resources/calico/10-cluster-role.yml
Labels: enhancement

#1049 Extract Host::ResolvConf and Route into separate files
  lib/pharos/autoload.rb
  lib/pharos/configuration/host.rb
  lib/pharos/configuration/network.rb
  lib/pharos/configuration/resolv_conf.rb
  lib/pharos/configuration/route.rb
  lib/pharos/phases/gather_facts.rb
  lib/pharos/phases/validate_host.rb
  spec/pharos/configuration/host_route_spec.rb
  spec/pharos/configuration/host_spec.rb
  spec/pharos/phases/configure_kubelet_spec.rb
  spec/pharos/phases/gather_facts_spec.rb
  spec/pharos/phases/validate_host_spec.rb
Labels: chore

#1058 Weave multi-cluster pod network
  lib/pharos/config_schema.rb
  lib/pharos/configuration/network.rb
  lib/pharos/phases/configure_weave.rb
  lib/pharos/resources/weave/01-cluster-role.yml
  lib/pharos/resources/weave/03-role.yml
  lib/pharos/resources/weave/06-flying-shuttle-cm.yml.erb
  lib/pharos/resources/weave/daemon-set.yml.erb
  spec/pharos/phases/configure_weave_spec.rb
Labels: enhancement

#1093 Use csi volume provider on digitalocean
  examples/terraform-do/cluster.yml
  examples/terraform-do/main.tf
  examples/terraform-do/pharos-addons/do-csi/addon.rb
  examples/terraform-do/pharos-addons/do-csi/resources/00-secret.yml.erb
  examples/terraform-do/pharos-addons/do-csi/resources/csi.yml
Labels: chore, documentation

#1095 Fix EL7 transport typos
  lib/pharos/host/el7/el7.rb
Labels: bug

#1098 Fix transport typo in ubuntu.rb
  lib/pharos/host/ubuntu/ubuntu.rb
Labels: bug

#1099 Simplify the config option copying for kubeconfig hint
  lib/pharos/command_options/load_config.rb
  lib/pharos/command_options/tf_json.rb
  lib/pharos/terraform/apply_command.rb
  lib/pharos/up_command.rb
Labels: enhancement

#1091 Fix DeepTransformKeys and spec
  e2e/drone.sh
  lib/pharos/core-ext/deep_transform_keys.rb
  spec/pharos/core_ext/deep_transform_keys_spec.rb
Labels: bug

#802 Refactor output colorization
  lib/pharos/autoload.rb
  lib/pharos/cluster_manager.rb
  lib/pharos/command.rb
  lib/pharos/command_options/load_config.rb
  lib/pharos/command_options/tf_json.rb
  lib/pharos/core-ext/colorize.rb
  lib/pharos/exec_command.rb
  lib/pharos/reset_command.rb
  lib/pharos/transport/command/result.rb
  lib/pharos/up_command.rb
  lib/pharos/version_command.rb
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: chore

#1100 Add ipalloc_default_subnet config option to Weave
  lib/pharos/config_schema.rb
  lib/pharos/configuration/network.rb
  lib/pharos/phases/configure_weave.rb
Labels: enhancement

#1103 The string colorization refactoring broke string.underscore
  lib/pharos/core-ext/colorize.rb
Labels: bug

#1101 License enforcement addon
  lib/pharos/addon_manager.rb
  non-oss/pharos_pro/addons/pharos-license-enforcer/addon.rb
  non-oss/pharos_pro/addons/pharos-license-enforcer/resources/01-license-enforcer-daemonset.yml.erb
  non-oss/pharos_pro/addons/pharos-license-enforcer/resources/02-rbac.erb
Labels: enhancement, pro

#1094 Update the pharos pro license assign to use the new JWT based token
  e2e/drone.sh
  lib/pharos/addon_manager.rb
  lib/pharos/autoload.rb
  lib/pharos/up_command.rb
  non-oss/pharos_non_oss.rb
  non-oss/pharos_pro/autoload.rb
  non-oss/pharos_pro/commands/license_assign_command.rb
  non-oss/pharos_pro/commands/license_command.rb
  non-oss/pharos_pro/commands/license_inspect_command.rb
  non-oss/pharos_pro/license_key.rb
  non-oss/pharos_pro/license_key_command_option.rb
  non-oss/spec/pharos_pro/commands/license_assign_command_spec.rb
Labels: enhancement

#1107 kontena-backup v0.9.11+kontena.1
  non-oss/pharos_pro/addons/kontena-backup/addon.rb
Labels: bug

#1106 Weave Net 2.5.1
  lib/pharos/phases/configure_weave.rb
Labels: bug

#1105 Kubernetes 1.13.3
  lib/pharos_cluster.rb
Labels: bug

#1113 Reconfigure kubelet on kubelet-config change
  lib/pharos/phases/configure_kubelet.rb
Labels: bug

#1114 Add dns-node-cache
  lib/pharos/configuration/network.rb
  lib/pharos/kubeadm/kubelet_config.rb
  lib/pharos/phases/configure_dns.rb
  lib/pharos/resources/node_local_dns/00-service_account.yml
  lib/pharos/resources/node_local_dns/01-configmap.yml.erb
  lib/pharos/resources/node_local_dns/daemonset.yml.erb
  spec/pharos/phases/configure_dns_spec.rb
Labels: bug, enhancement

#1112 Export complete HTTP proxy environment
  lib/pharos/scripts/pharos.sh
  lib/pharos/transport/base.rb
Labels: enhancement

#1078 Also run OSS specs during NON-OSS spec run
  .drone.yml
  lib/pharos/version.rb
  non-oss/pharos_pro/version.rb
  non-oss/spec/pharos_pro/commands/version_command_spec.rb
  non-oss/spec/pharos_pro/phases/validate_version_spec.rb
  spec/pharos/phases/validate_version_spec.rb
  spec/pharos/version_command_spec.rb
Labels: chore

#1045 Add dev gems to Gemfile, drop Gemfile.lock from VCS
  .gitignore
  Gemfile.lock
  lib/pharos/configuration/route.rb
  lib/pharos/transport/command/result.rb
  lib/pharos/transport/ssh.rb
  pharos-cluster.gemspec
Labels: chore

#1115 Fix license-enforcer addon manifests
  non-oss/pharos_pro/addons/pharos-license-enforcer/resources/01-license-enforcer-daemonset.yml.erb
  non-oss/pharos_pro/addons/pharos-license-enforcer/resources/02-rbac.yml.erb
Labels: bug, pro

#1117 Fix failing addon manager spec
  spec/pharos/addon_manager_spec.rb
Labels: bug

#1119 Increase kontena-backup restic daemonset limits
  non-oss/pharos_pro/addons/kontena-backup/resources/30-restic-daemonset.yml.erb
Labels: bug, pro

#1120 Cri-o v1.13.1
  lib/pharos_cluster.rb
Labels: bug, enhancement

#1124 dns-node-cache v1.15.1
  lib/pharos/phases/configure_dns.rb
  lib/pharos_cluster.rb
Labels: bug, chore

#1118 License-enforcer addon v0.1.1
  non-oss/pharos_pro/addons/pharos-license-enforcer/addon.rb
  non-oss/pharos_pro/addons/pharos-license-enforcer/resources/02-rbac.yml
Labels: bug, pro
