Repository kontena/pharos-cluster, pull requests merged in 2019-10, with the labels that each got.

#1484 Update k8s-client to 0.10.4
  lib/pharos/addon.rb
  pharos-cluster.gemspec
Labels: chore

#1487 RHEL 7.7
  lib/pharos/host/el7/rhel7.rb
Labels: bug, chore

#1483 Use stable ceph-mon endpoint in cephfs storageclass
  non-oss/pharos_pro/addons/kontena-storage/addon.rb
  non-oss/pharos_pro/addons/kontena-storage/resources/16-mon-service.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/41-role.yml
  non-oss/pharos_pro/addons/kontena-storage/resources/43-deployment.yml.erb
  non-oss/pharos_pro/addons/kontena-storage/resources/44-storageclass.yml.erb
Labels: bug, pro

#1492 Kubernetes v1.14.7
  lib/pharos_cluster.rb
Labels: bug
