Repository kontena/pharos-cluster, pull requests merged in 2019-09, with the labels that each got.

#1318 Fix kubelet proxy configuration race condition
  lib/pharos/configuration/host.rb
  spec/pharos/configuration/host_spec.rb
Labels: bug

#1473 Use patched hcloud-csi-driver
  lib/pharos/resources/hcloud/hcloud-csi.yml.erb
Labels: bug

#1471 Kontena Lens addon: bump user management to 1.6.2
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: bug, enhancement, pro

#1475 Fix firewalld "inactive (dead)" problems
  lib/pharos/host/debian/scripts/configure-firewalld.sh
  lib/pharos/host/el7/scripts/configure-firewalld.sh
  lib/pharos/host/ubuntu/scripts/configure-firewalld.sh
  lib/pharos/resources/calico/25-node-daemonset.yml.erb
  lib/pharos/resources/weave/daemon-set.yml.erb
Labels: bug

#1480 Fix node-exporter service selector
  non-oss/pharos_pro/addons/kontena-stats/resources/11-node-exporter-svc.yml
Labels: bug

#1485 Update k8s-client to 0.10.4 (2.4 backport)
  lib/pharos/addon.rb
  pharos-cluster.gemspec
Labels: chore
