Repository kontena/pharos-cluster, pull requests merged in 2019-08, with the labels that each got.

#1435 Kontena Storage: ceph-prom-exporter v0.3.0
  non-oss/pharos_pro/addons/kontena-storage/resources/51-ceph-prom-exporter-deployment.yml.erb
Labels: bug

#1437 Fix apiserver cert recreate
  e2e/drone.sh
  lib/pharos/phases/configure_master.rb
  lib/pharos/scripts/kubeadm-renew-certs.sh
Labels: bug

#1442 Tunnel K8s API client to master's localhost:6443
  lib/pharos/phases/configure_client.rb
  spec/pharos/phases/configure_client_spec.rb
Labels: bug, enhancement

#1444 CRI-O v1.14.6
  lib/pharos_cluster.rb
Labels: bug

#1445 Kubernetes v1.14.5
  lib/pharos_cluster.rb
Labels: bug

#1440 Fix hostname and address uniqueness validation for hosts sharing an IP
  lib/pharos/config_schema.rb
  lib/pharos/phases/validate_host.rb
  spec/pharos/command_spec.rb
  spec/pharos/config_spec.rb
  spec/pharos/phases/validate_host_spec.rb
Labels: bug, enhancement

#1447 Remove invalid cert-manager-webhook:auth-delegator role binding
  addons/cert-manager/resources/03-roles.yml
Labels: bug

#1450 Kontena Lens: bump authenticator & user mgmt to 1.6.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: bug, pro

#1453 Ignore expired SSL certificate when prefilling cache
  lib/pharos/phases/configure_client.rb
Labels: bug

#1455 cert-manager 0.8.1
  addons/cert-manager/addon.rb
Labels: bug, enhancement

#1420 Fix "can't modifyf frozen String" in worker up param handling
  lib/pharos/worker_up_command.rb
Labels: bug

#1462 Ingress-NGINX addon: update to v0.25.1
  addons/ingress-nginx/addon.rb
Labels: bug

#1461 Kubernetes v1.14.6
  lib/pharos_cluster.rb
Labels: bug

#1464 Fix pharos reset worker NoMethodError
  e2e/drone.sh
  lib/pharos/reset_command.rb
Labels: bug

#1457 Kontena Stats addon: fix node-exporter on hybrid clusters
  non-oss/pharos_pro/addons/kontena-stats/resources/10-node-exporter-ds.yml.erb
  non-oss/pharos_pro/addons/kontena-stats/resources/11-node-exporter-svc.yml
  non-oss/pharos_pro/addons/kontena-stats/resources/50-etcd-scraper-proxy-ds.yml.erb
Labels: bug

#1468 Fix ingress-nginx rbac issue
  addons/ingress-nginx/resources/02-cluster-role.yml
Labels: bug

#1470 Kubernetes v1.15.3
  lib/pharos_cluster.rb
Labels: enhancement

#1466 Update Kontena Lens to 1.9.1
  non-oss/pharos_pro/addons/kontena-lens/addon.rb
Labels: enhancement
